class Expression < ApplicationRecord
  has_many :charts
  has_many :users, through: :charts

  def short_description

     if self.number == 1
  "Number 1 as an Expression number is a symbol of inborn leader. Your life will be oriented on development, freedom (so it is important for you to be financially and personally independent), constructing your life plan. Your name can be useful for you during your life, and help you reach high step on a professional ladder. You obtain strong power of will, and it should be used and directed on your goals. Try to use every possibility you have. The critical mind and ability to broad analysis that you have are the keys to your success."
    elsif self.number == 2
  "Working with others is your forte. Your 2 Expression makes you very skilled in relationships of all kinds, because it is cooperative, supportive, and always striving for balance. You have a keen ability to read people and situations and react with patience and understanding. Others see you as peaceful and humble, yet there is great strength in you. Still, your feelings can be easily hurt and you have a tendency to doubt yourself when making decisions, which can make you idle. You would benefit from following your head instead of your heart from time to time."
    elsif self.number == 3
  "With the influence of the number 3, you are a naturally skilled communicator. You have a way with words and a great talent for conveying your creative ideas and inspiring others. Your social circle is strong and people find your optimistic attitude both magnetic and charming. However, the relationships you form, like many other things in your life, don't go very deep. Your enthusiasm for life can be a distraction, making you unable to stay focused on one person, job, or plan long enough for it to develop into something complete or meaningful."
    elsif self.number == 4
  "Organized, down-to-earth, and hardworking, the 4 Expression gives you skills that make you incredibly capable and constructive. You are a master at managing projects and teams and others rely on you because you follow everything through to completion. You are honest, patient, and loyal -- sometimes, loyal to a fault. The number 4 carries a stubborn, rigid energy that can make you so fixed in your ways that you are unable to grasp new, better ways of thinking, doing, and interacting."
    elsif self.number == 5
  "Your 5 Expression craves variety and freedom and wants to experience everything that life has to offer. You are an adventurous person who takes pleasure in trying new things and following your latest passion. Your passions change quickly, however, so you've learned to switch gears easily in order to explore as many possibilities as you can. Beware, though, that with all this change comes inconsistency. Your restlessness can make you unreliable in relationships and unprepared to handle the hardships of life."
    elsif self.number == 6
  "Your strengths play out most notably in your relationships with others. The influence of the number 6 makes you incredibly protective and nurturing toward all people, but especially your family members and other close loved ones. You have a heart of gold and feel a responsibility to be there to help those in need of support. It's important, though, that you don't forget about self-care. You can be so focused on the well-being of others that you neglect to attend to your own emotions and energy levels. Be kind to yourself, too."
    elsif self.number == 7
  "You are the truth seeker. You are energized by information and willing to go deep into both the intellectual and spiritual realms in search of real meaning. Logic drives the way you think and communicate, and this helps you clearly convey your vast knowledge to others. You are not satisfied with what's on the surface -- it's the hidden answers you are digging for. However, this assumption that there is always something to be found can make you suspicious of others. In fact, it may be hard for you to relate to other people in general; you tend to prefer a controlled environment where you can do things your own way."
    elsif self.number == 8
    elsif self.number == 9
    elsif self.number == 11
    elsif self.number == 22
    elsif self.number == 33
    end

  end

  def long_description

    if self.number == 1
  [
  "With a 1 Expression number, you possess strong leadership capabilities and a knack for creating your own opportunities. You will go where others are afraid to go and you'll make the journey look easy. The number 1's energy is extremely self-sufficient, allowing you to be most innovative and productive when you're working alone. You may even find it difficult to cooperate with others, preferring to do things your way rather than listening to anyone else's opinions. If you aren't careful, the 1 Expression could make you seem aggressive and self-centered. It's not in your nature to think before you speak or act, but you would be wise to learn this skill!",

  "Pay attention to your Life Path number, it may turn out that you need a mentor or a guider, if you need a help - ask for it. However, in most cases you are a person that leads and shares the knowledge and experience with others. You are an authority and inspiration for some people around. You easily sort out the details and are stress-resistant in important moments, though your emotions take over sometimes. It is very important for you to implement you skills and express your professional ability in your career. You should put all your strength now to realize your potential in the future. Always search for different possibilities to present the innovative ideas you have. Your life is like well-thought strategy where you are always on the step ahead. People with your disposition are usually favored by the Universe: they own a business, run a company and are independent and self-sufficient. You strongly believe that hard work and efforts can help to break through. When you are mature enough, you will have to know already what you want from life and what are your main desires. The other important aspect is confidence. No one but you is responsible for your success, and you need to be sure that you'll succeed, as things will be as you believe them to be. You are ambitious and curious person, sometimes it seems like you can't spend a calm week. However, you easily lose interest. Also, the other side of the confidence is self-assurance that is manifested by narrow mindedness and stubbornness.",

  "Ones are known for their patience and persistence. They are happy, materialistic, driven, clever, attractive, independent, sincere, focused, logical and intelligent. Since ones are fruitful in life, they should couple these qualities with a sense of humor. Maintaining the ability to relate to others through humor keeps them grounded, and allows ones to avoid egocentricity and superiority. Mistakes are rare, but when they do happen, it causes ones extreme frustration. However, errors can be a helpful dose of reality to combat self-centeredness that often accompanies success.",

  "With maturity, ones only get more ambitious and determined. Their drive, focus and ambition that expression number 1 people posses mean they will excel in positions of power. They will likely be CEOs, entrepreneurs, executives or promoter. They are problem solvers that are quick to act. These qualities bode well in positions of importance. A one’s purpose in life is to solve problems. Issues involving the environment and psychology allow them to thrive and make the greatest differences in the world around them. However, they are fiercely independent. They do not work well within a group because they will thwart others.",

  "Their aggressive nature makes them difficult to live with. People possessing a destiny number one aren’t what you’d consider romantics, but are very loyal in marriage. Ones desire companionship and will often have many relationships before settling down. This is a direct result of having overly high expectations of their mates. They tend to be single-minded, often focusing solely on their careers because they thrive on success that is quantifiable. They expect praise and encouragement from their mates, but often don’t reciprocate those acts. Their relationships get thrown on the backburner because their immense desire to be successful professionally.",

  "This destiny number is associated with excellent health and spiritual wellness. Ones are considered to be lucky and clairvoyant.",

  "Since ones frequently spend their life in a position of power, they can have very large egos and appear pushy. If a one loses their humility they can become incorrigible and self-destructive. Their hunger for success can result in unachievable goals, and this can lead to frustration as well as low-self esteem. A one’s fear of being “caught in a rut” makes them quick to jump the gun to avoid a monotonous lifestyle. Their aggressive and domineering nature has the tendency to make them difficult to relate to, which means they will appear self-centered and egotistical. Creating a tactical plan can help ones to achieve goals without the need for excessive forcefulness. Learning to manage a balance is vital to maintain relationships."
  ]

    elsif self.number == 2

  [
  "Number 2 as an Expression number shows that sociability and interrelationships will play major role in your life. The letters of your name create a combination that in refers to the person who is able to understand people deeply and comfort them in times of trouble. You can make a great psychotherapist, peacemaker or diplomatic worker. Through the years, you can find yourself to be skillful in eloquence and especially delicate when it comes to interrelationships. Number 2 that also corresponds to master number 11 (2) is a very strong number. People under such number are inspirational and easily encourage others on important decisions. The inner power you have makes you a gifted tutor, philosopher, consultant, social activist, diplomat, and worker in any rescue center. No matter what career path you choose, you are skillful professional that inspires people around. You are very sensitive to the surrounding world and it reflects on your intuition: it is well-developed.",

  "You are a good team player, but bad lone player. Working in a team you guide others and express yourself this way and it is a reason of your success. Boost your self-confidence in order to become more independent from social opinion, and feel more secure by yourself. Injustice is often in our world, and a lot of people will be rewarded for your ideas and input, but don't worry, you express yourself in team, so just do what you do best. Your principles and ideas are more important than social appraisal. After you've become more confident, people will be magnetized by your change, so take your chance to establish your life the way you want it. You have mature set of principles to which you adhere, and it is great, because principal people are solid in their beliefs and confident in their mind and skills.",

  "However, the other side of number 2 is oversensitivity. That is why you need to boost your confidence, so you are more protected from social triggers that can hurt your delicate soul. It is normal to be sensitive, but in our world some protection mechanisms are needed. If you have many 2's in your chart it may cause you to be lazy and apathetic to the world around. In some cases, number 2 (especially derived from master number 11) suffer from uneasiness and overemotional reactions. Try to keep balance in everything you do. You are a dreamer, and you often prefer dreams to grey realities. Be careful and try to make decisions with a clear mind and precise wants from life.",

  "Twos are gentle, diplomatic, adaptive, calm, sensitive, considerate, emotional, detailed and balanced. They are socially intuitive and supportive. Their friendly nature helps others to feel comfortable around them, and they despise arguments. Their gentle nature makes them overly sensitive in disagreements, and twos will experience low self-esteem in relationships that involve a lot of arguing. They’re keenly aware of the needs of the people around them, which means friends are never in short supply. Twos find that the nicer things in life are necessity, but they also value the small, kind gestures of others. They have an artistic vigor, and later in life they’ll find comfort in meditation and the outdoors. Twos generally have excellent self-esteem, and strictly follow the golden rule, which makes friends easy to come by. Positive life circumstances will allow them to grow and shine. The same qualities that make twos excellent at negotiating can also make them appear weak, submissive and indifferent. They fear quarreling and unplanned changes, as well as being alone and making errors.",

  "People with the destiny number two are lovers of the arts, and that naturally makes them excellent actors, dancers, poets or writers. Since twos are also nurturing and selfless, they will excel in the healthcare field. Jobs like nursing, psychiatry, social work, teaching and doctoring are positions that fit twos well. Career choices and voluntary pursuits that benefit others put twos in a position to prosper.Since quarreling doesn’t bode well for people with these destiny numbers, any job involving a competitive working atmosphere will be uncomfortable.",

  "Expression number 2 loves deeply, intimately and effortlessly. A partner that doesn’t appreciate a two’s kind and nurturing nature will take advantage of them. However, being in a relationship with a person who is too dependent will end in failure, too. If they are wronged twos will often promise not to love again, but these feelings subside quickly. It has been reported that twos often have issues with mental wellbeing. They’re indecisiveness can often cloud their mind and make them disillusioned. Reality and fantasy merge and they becoming unreasonable, which results in mental unbalance. Twos that are overly sensitive struggle with nervous tension, too.",

  "Since nurturing and keeping the peace are integral parts of a twos psyche, maintaining patience, balance and tolerance is important to their overall happiness. Being true to their inner calling is important to remember, but not at the sake of losing themselves. Because they are often so focused on others, they put their own needs and desires on the backburner. Learning to balance the scale is vital in order to live a happy, stable and fulfilling life."
  ]

    elsif self.number == 3

  [
  "People born with expression number three are built for arduous work. Their strong bodies are built to maintain the pressures around them, and they’ll likely test that theory frequently during their lifetime. They’re born lucky, which saves them from being involved in accidents and falling short financially. Threes are multi-talented, creative, energetic and artistic, and they will grow creatively and spiritually throughout life.",

  "Expression number 3 means that your life is closely connected with creativity and artistic expression. Number 3 implies developed power of will, ability to self-analysis and acceptance of criticism. You need to be ready to be on stage and provide positive emotions for your audience. People with this number are so energetic that why are we still searching for the source of eternal energy, when we have threes. The main role for you to play in your life is to inspire people around, to make small things that mean a lot, or to influence from the large stage to the audience. People with Expression number 3 can make brilliant artists, actors, musicians, teachers, singers, and dancers. No matter what profession you choose to live by, you will always be interested in artistic expression.",

  "The creativity of your mind can be manifested in professions connected with analyzing of needs and desires of people. Marketing and promotion are spheres friendly to you. With your charm you can make a person buy or pay attention to any product or company of your interest. Develop these skills, and you'll see how drastically your life can change. It is a pleasure to hear you talking about sphere of your interest, because you automatically make it so attractive that people around can hardly pass by. Due to your level of energy and wit of mind you can support many topics and make reasonable statements if it comes to arguing. Inspiration for you is a key to everything. When you are inspired you are motivated to act, and it always brings you profit. Keep closer to your friends. Despite your character and talkativeness you don't have many true friends, so if you have that one friend it is valuable. Also, learn to be a friend in return. Through years, when your mission is understandable for you, you will become more social and open. The only essential shortcoming of this number is inability to concentrate on one thing for a long time, so all the efforts you've done before are in vain when you quit it.",

  "Threes are imaginative, responsible, talented, outspoken, optimistic, good-natured, generous, loyal and charming. Their energetic nature and stamina allow them to maintain large workloads and pressure. Threes are born leaders, but they don’t frequently seek the limelight. Their leadership instincts and dedication to their career help threes excel in handling extreme work stressors. They also have a magnetic charm, which means they constantly make new friends and supporters. Threes are excellent conversationalists. Their love for life encourages, motives and inspires others. Threes are foodies who enjoy the comforts of home. It is possible for a three to spread themselves too thin. Keeping and maintaining friendships are of the utmost importance to threes, but they should not waste time worrying over trivial things. Their self-sacrificing nature can hinder their growth, and their drive to be financially successful might make them appear superficial. It is possible to develop an addictive personality if money is spent wastefully.",

  "People with destiny number three will earn money through different ventures during life. Their leadership skills, charm and work ethic make them popular and well suited for politics. Threes are also predisposed to excel in fields like business, sales, education, religion, advertising, publishing and tourism. Their giving nature will lead them to philanthropic endeavors later in life. They take pride in working hard to help others. Threes also have a love for the arts, but only a few will select a field that puts them on stage.",

  "People with expression number 3 not only have great friendships, but they also have a strong family bond. Their charm makes them an exciting lover, but they can lose interest quickly if their mate becomes boring. A weakness for sex may make them unlucky in love. This weakness may also cause various affairs. A three’s partner will devote all their time toward creating domestic balance. Thus, the three can spend ample time working on their career. Since a three’s career and life will likely be spent in the company of others less fortunate, they must develop a compassionate nature. They must seek a clearer understanding of others to be fruitful. Coupled with clarity, a three must also capture the ability to be a true friend. Keeping and maintain friendships will be a huge part of a three’s life, and success will only be gained after learning the true value of companionship. Since money will flow easily from multiple sources for most people with destiny number three, they must learn to avoid overindulgence. Threes should fight the urge to be wasteful, and instead learn to live in moderation. Becoming monetarily over excessive will lead to an addictive nature and financial hardships."

  ]

    elsif self.number == 4
  [
  "Number 4 as an Expression number shows that your life is oriented on the career, leadership, sense of order and justice. Through the years you will become more pragmatic, realistic, skilled in your professional area and detail-oriented. You are a perfectionist in some way, and it will be reflected on your work so everything is done brilliantly or never done. You have a lot of future possibilities to succeed in spheres of exact sciences if you are keen on details. You can make a nice teacher, but also in spheres of crafts and exact sciences, because you are easygoing and ready to share the knowledge you are master at. Even if you are an artistic nature, your art is technologically oriented or well and precisely thought. Try yourself in interior design and planning, in landscape design, graphic design and architecture. By the way, many skillful surgeons have number 4 as an Expression number. You can easily work at any field where arrangement, calculation, management and precise estimation are needed.",

  "People with number 4 are usually very initiative, especially if number 2 comes from master number 22. They are skillful entrepreneurs and love to make their job done on the highest level. They also love to hear compliments regarding their professional achievements, because it compliments not the beauty that is given naturally, but the achievements that are gotten by efforts. It is hard to be your friend, because you search for the best in people and demand best from yourself. Such high standards are rare nowadays. You are very principled and critically estimate information that comes from other people. You can make friends with people of high moral standards and witty disposition.",

  "People with destiny number four (aka ‘expression number 4’) often work as the stabilizer. They are cerebral beings that worship order, organization, management, discipline, routine and rules. Fours can easily take on difficult or unpleasant tasks because their desire to share wisdom and knowledge. They are extroverts that work well alone and with others. Success is quantifiable by comprehension and wisdom earned. They have a huge appreciation for their home and they seek security.",

  "People with destiny number four are organized, patient, dignified, dependable, honest, devoted, determined, loyal and hardworking. They hold true to traditional values and appreciate order and having a system. This number is ruled by a cerebral power, and they thrive when they are putting new ideas in order. A four will work steady toward any goal with a detailed plan. They are productive, hard workers and remain neutral in most situations. Their extroverted nature works in tandem with their strong moral compass. The combination allows this person to be easily relatable and harmonious.They consider creating a foundation their duty. The base they construct is often built from patience and perseverance. They value security and work to protect themselves and others. Because of their need for order, they lack the ability to adapt to new situations. They’ll frequently miss out on excellent prospects because they dislike change. They’re homebodies so they can become prone to laziness.",

  "Expression number 4 people are inclined to make money in a variety of ways, but they will also spend wastefully. They are often work-oriented because they always have a plan of attack. A four’s need for structure bodes well in managerial and HR positions. They are realists that value honesty. They’re also highly intelligent and analytical. Careers in fields like engineering, production, computer science, mathematics and astronomy are also an excellent fit for a four. A person that has a destiny number four considers their home their sanctuary. Fours value a strong family support system, and they will maintain loyal to their partner and family. Sharing the simple pleasures in life with a supportive family gives them great pleasure and balance.",

  "There are several areas where a four must learn flexibility to reach their full potential. A four must learn to maintain balance when adjust to change. They often get so set in their ways that a slight deviation will cause them to detest their life. Fours need time to adjust to things methodically, but this can appear to others as uncompromising. They can become argumentative and aggressive if they’re patience is pushed. Their active minds make them doubtful. When meeting new people or being thrust into unknown terrain, they will become suspicious and pull back into their shell. This factor will cause them to miss many fulfilling opportunities throughout life. A four thrives on acknowledgement, but they don’t often get it. Their work will suffer immensely, often never getting finished. Without praise, a four will never find satisfaction in their work life, and this leads them to change professions frequently."
  ]
  elsif self.number == 5

  [

  "People born with destiny number five (aka ‘expression number 5’) sit in the middle of the destiny numbers. They are flexible, and desire the freedom to act when they deem fit. They are non-conventional will not be tied down. Fives will see and experience more than any other vibration in numerology. Their curiosity and need for change will encourage many adventures, experiences and opportunities.",

  "Number 5 is a sign of activeness, desire to change and to be always in the center of events, creativity and independence. Those who have number 5 as their Expression number are really lucky, as they pass through many lucky possibilities in their life. To extract the best features of your number you will have to learn to set priorities, to concentrate on needed things and to use your time in a right way. You will have a freedom of choice, and when time comes you need to make a proper one. You will have to become flexible and fit into different situations. Through years you will learn how to use your charisma with profit, in other words you will be able to manipulate people, to make them adhere to your position. It is especially useful if you chose a profession where you need to persuade people to buy something. You are intellectual and think and react quickly regardless of situation.",

  "Hold on for innovations, you will have a lot of possibilities if you attentively follow trends and react on them. You need to catch the right wave and you will become successful and will be able to express yourself fully. It is natural for you to be curious and innovative. You are always surrounded by people, because you are a great listener and you can easily imagine yourself in someone's shoes, it is your kind of intuition. This number is great for many career choices, as you are intelligent and easy to teach. Look closer to work directly with people, because you know how to cooperate and persuade them. Advertising, radio and television, journalism, psychotherapist, and business management are the fields where you have a lot of chances to succeed. You are a competitor, you need new emotions and new goals quite often, so it is normal for you to change working places.",

  "If 5s appear frequently in your chart some negative features of number 5 may be present. You are very changing person. A lot depends on your mood, so you need to learn to cool your temper sometimes. Also you tend to scatter on so many things at one time that you rarely finish something. It may be useful for you to become more disciplined if you want to reach particular goal. Try to avoid prejudices and superficial thinking.",

  "A five sees every opportunity as an ability to grow, and will often become independent at an early age. They are opportunistic, curious, energetic, persuasive, outgoing, charming, imaginative, intellectual, unconventional and fun. Having a routine is like being imprisoned for a five. They desire the freedom to do, say and experience things as they see fit, and will only thrive in these conditions. They enjoy impulsiveness and pleasure, and this often leads to over-indulging. Fives will express themselves in unique ways, and they do not follow the status quo. These people are eager to adapt and welcome change. An unwavering curiosity will cause them to start one task and quickly switch gears to something else. They love the arts, travel, sports and new places and things. Often playful, witty, energetic and fun, a five enjoys casual flirting and is always the life of the party. They thrive being the center of attention. If a five feels tied down, they’ll often stir up trouble to fill the void. Since they detest routine, learning to adjust to general responsibilities will make this person unhappy and uncomfortable.",

  "Since expression number 5 people hate to be tied down, work is considered a means to an end for fives. They constantly seek freedom, and will not feel a commitment to their workplace is important. They are not inclined to tackle work-related problems. Instead, they’ll move on to another job. Fives are capable of solving almost any problem on their own because of their independent nature. This quality makes them excellent journalists, teachers, freelancers, writers, judges, politicians, speakers, artists or business people.Their curious and adventurous spirit makes many fives pioneers. Their quick and sometimes irrational decision-making works well in fields like exploring and inventing.",

  "People with the destiny number five have difficulties settling down. Their fear of confinement often causes them to discard things and people quickly. Their need for constant change and transition means they have many friends, but very few good ones. Smothering relationships, in any form, do not work for fives. They’ll have numerous relationships because they have many admirers. To make a relationship work a mate must learn to accept the five’s impulsiveness nature and desire for freedom. A five is happy to share the good things in life, and the relationship is often a happy and harmonious one. A declaration of love, which doesn’t come often, is an indication of their desire for commitment. A five must strive to rein in their impulsive nature. Because they’re quick decision makers, they do not weight and measure the consequences for their actions. This characteristic often ends up hurting others."

  ]

  elsif self.number == 6

  [

  "Expression number 6 is usually associated with family values, kindness, love, responsibility and openheartedness. Through the years you will be experienced in communication with people. You will be especially concerned about those, who weren't lucky enough in this life. You will be skilled in problem-solving and ready o give an advice to anyone who needs it. It is in your nature to work with and help people. You can make a great parent. You are caring, loving and soft person, though you have strong character and you are hard to stop when you've planned something. You are empathetic and nice to talk to. You are honest, but not rude, such type of harmony is rare. You love comfort and you feel comfortable only at home, where you are relaxed and surrounded by close people. It is obvious that you are a nice friend, you accept people for who they are without judging.",

  "Number 6 is often a sign for wealth. You are artistic person and need some artistic expression, but your career path would probably be connected with another sphere. You can express yourself best by communicating and helping others. It is your mission in life, because you care, because it is important to be less selfish in our world. Number 6 are great teachers, psychologists, doctors, firefighters, social workers, and consultants. Such people are interested in design and decoration, because they like to be surrounded by beauty. Some negative features are also present in number 6, especially if there are a lot of repeated 6s in the chart. Sometimes people with number 6 care too much so that they are annoying or disturbing others. In other cases such people are obsessed with control, so everything is perfect. They often forget that the notion of #{"perfection"} is different for people. You need to learn to accept criticism with dignity, without lowering your self-esteem because of someone's opinion.",

  "People born with the destiny number six are caring, protecting, graceful, loving, charitable, nurturing, balanced, reliable, compromising, faithful and honest. They are often too self-sacrificing, and will never expect any payment or acknowledgement for their actions. Because of their instinctual need to help others and their trusting nature, they’re often taken advantage of and can be a terrible judge of character. They’re well-liked for their warm, friendly personality. Sixes will always favor the underdog and are eager to right wrongs, even if that means being a bit of a perfectionist. If a six becomes too focused on rectifying smaller issues, they can lose sight of the bigger picture. Their infatuation with seeking truth can come off to others as slightly self-righteous. Often considered the most harmonious among all the destiny numbers, if a six falls into emotional of physical conflict, they can become the most destructive of all the numbers. A person with this number loves to teach and guide, and will likely take on a role as a caregiver to the young, old, handicapped or less fortunate. This person can always be held accountable for their fair share. They’re willing to contribute their part, plus some.",

  "Expression number 6 people will thrive in a position that allowed them to flex their negotiating muscles, but not in a competitive arena. A person with the destiny number six will excel in the arts, promoting, fashion or beauty. Their love for people and the less fortunate can also lead them to careers in community service, ministry, counseling, law enforcement, nursing or teaching. A six must remember to create standards that can be met. Their predilection for setting goals too high comes off demanding and can cause them to be over critical of themselves. Sixes must learn to take things at face value. Developing this skill will allow them to avoid getting too attached to people before they show their true colors.",

  "A six is driven by love, and considering their attractiveness and sex appeal; they have no issue finding people to flirt with. Sixes dislike living alone and believe that all domestic relationships are meaningful, but often find seeking a mate difficult. People with other destiny numbers are often dissuaded by their looks, and a six is often a terrible judge of character. They aren’t usually comfortable displaying affection frequently because they fear rejection. Sixes have deep-rooted anxiety and insecurities, and this can often result in a variety of phobias. They obsess over little details, which can also cause OCD."

  ]

  elsif self.number == 7

  [
  "People born with the destiny number seven (aka ‘expression number 7’) are wise, warm and compassionate. They can easily weigh and measure the elements of a situation to reach a rational approach that works best for everyone. However, they often underestimate their skills. They have analytical minds and a thirst for knowledge, but they usually prefer working alone, though they have many admirers. Throughout life, sevens will get in touch with a more spiritual and mystical side of the world. Many sevens can even develop clairvoyance or other psychological gifts.",

  "Number 7 as an Expression number shows an analytic, pragmatic and intellectual person. You are direct and honest, so you demand it from people around. You can make a great judge or journalist. You are very attentive and curious that in combination with analytical skills makes you understand things profoundly. Though you see more, you never try to disturb others or violate their privacy. Your curiosity and sense of justice let you seek for information that is important for everyone, especially if it is hidden. You always see more than others, so you are on one step ahead in every situation. If you are keen about something, you will become almost a professional in it, because you will start to read, to learn more and to investigate. You can be a teacher that changes lives of the students, as you are so inspirational and energetic that it is hardly to find someone better for guiding people.",

  "You are a weirdo for some people just because they can only guess what you are thinking about. During your life you can be identified as friendly and positive person in harmony with yourself and the world. You care about your privacy and don't want strangers in your life. This number has pleasant positive features. You like logical order in everything, so you always know where you can find anything at your house, the same is about the structure of your mind, as you have logical associations with things you need to remember. However, you can be too logical and rational that you protect yourself from emotions, even if you deprive yourself of something good. If you have a lot of 7s in your chart it may be manifested through lack of trust to other people and emotional estrangement. Due to such aloofness you can be an introvert in the most negative meaning of this word, you may be alone as a result and feel lack of warm communication.",

  ""

  ]

  elsif self.number == 8

  [

  ]

  elsif self.number == 9

  [

  ]
  elsif self.number == 11
  [
  "You have a deep desire to reach for higher states of consciousness, and on your way there, you must learn to develop authentic and satisfying relationships. Look deep into your soul, you’ll see that you have an underlying need to evolve spiritually. But there’s a catch. With the number 11 as your Soul Urge, you’ve got your work cut out. It will be hugely beneficial for you to realize at the offset, that your soul’s mission will truly take a lifetime of development, so pace yourself. Your heart’s desire requires deeply felt experiences and through the course of your life, you will be tested over and over again. The ultimate lesson of the Soul Urge Number is that life is a marathon, not a sprint. There is an ongoing irony attached to Master Numbers, because on discovering numerology, many people want to see Master Number drawn up in their chart, thinking that a Master Number is somehow superior to a “regular” number. Untrue. A Master Number indicates that before incarnating, you opted into this lifetime on Earth with higher potential, yet with more intense challenges. These challenges will often manifest as life-long feelings of internal (and sometimes external) nervous tension, feelings that you’re never doing enough, being enough, doing it right, or living up to your potential. Yet those with Master Numbers are the ones being called upon to step up and take the lead in some fashion, to think bigger, and to make a mark, so it’s not an easy road. So if you’re working through life with a Master Number, don’t expect it to be easy … And if you’ve yet to decode your personal numerology chart, be careful what you wish for! There’s an undeniable intensity related to carrying the Master vibration, so it’s extremely important to know how to optimize and manage it, so you don’t crash-and-burn. Attempting to shine too brightly too rapidly, or suppressing, sublimating or ignoring your mission can both be painful routes to self-sabotage, and need to be avoided…",

  "For you with an 11/2 Soul Urge, it means that the foundational energy of your deep desire resides with the number 2. You’re a mediator, a diplomat, and a curator of love and relationships. You express incredible emotional sensitivity and are the master or mistress of patience. But in addition to this, you contain the master number powers of the 1, in double intensity! The 1 is concerned with YOU, and making a mark in the world, coming first and championing above all else. The 1 contains the driving energy of initiation, leadership, innovation, independence, and is often the quirky individualist. The 1 seeks to take the lead while the 2 seeks to be the supportive power behind the throne. It’s as though you’re a Siamese twin, yet your twin is the Yang to your Yin.",

  "You bring a heightened and refined energy to whatever you do and yet here is the inherent frustration: What you bring to the mix is somewhat intangible. And therefore it’s difficult to trust that you’re on task or having any significant impact because what you do best is primarily etheric and energetic. You’re a messenger, but one of the spiritual kind. As an example or a metaphor, let’s say you’re an artist – a dancer. You perform for an audience and many people come to watch you. As they experience the way you move, there is something that is affected inside of the person watching – something changes, something that even they don’t understand, let alone are able to enunciate. Yet your work has shifted them in an unspeakable way that will be a part of their lives forever.",

  "Underneath it all, you are the “wounded healer” and your gift is to serve as an inspiration to evolve, in whatever form you choose. This may be through parenting, your career, your devotion to pets or causes, or any other aspect of life where you feel a deep connection. Know that you have gifts in the realm of artistic creativity. You’re at your optimal when acting upon healthy emotional and energetic boundaries, serving the needs of a group dynamic, and developing your relationship with yourself, with others, and with the spiritual realm. The Soul Urge 11 is a powerful number, demanding that you learn how to level your ego, trust your intuition, and serve as a conduit for spiritual energy to move and speak through you.",

  "Your compatibility in relationships will depend very much upon your partner’s patience and understanding of your spiritual quest. But this isn’t to say relationships should be neglected – one of the missions of this master number is to understand the intricacies of creating and maintaining a healthy and successful relationship. Because of this, you may find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher. Your most compatible numbers are the 1, 2, and the 22. Your least compatible numbers (though the ones where you have most to learn) are the 3 and 5.",

  "Know that your 11/2 Soul Urge is a profound journey that offers you multifaceted opportunities to create loving environments, dig deep into relationships, and bring an evolved and spiritually heightened energy to all of your interactions. At your core, you’re a spiritual messenger who is highly intuitive, probably psychic and certinly and creative. But with the number 11/2 as your Soul Urge, this may be something only you can see or feel. Or alternately, you may tap into your loving diplomacy, heightened creativity, and super-charged spirituality in a hugely substantial way. As with all of numerology, it ultimately depends on the other numbers in your chart and how those energies mix and match with your inspired and spiritually focused number 11/2."
  ]

  elsif self.number == 22

  [
  "When you look deep into your soul, you have an underlying and pressing need to evolve spiritually. But there’s a catch. With the Master Number 22/4 as your Soul Urge, you’ve got your work cut out. It will be hugely beneficial for you to at the offset, that your soul’s mission will truly take a lifetime of development, so pace yourself. Your heart’s desire requires deeply felt experiences and through the course of your life, you will be tested over and over again. The ultimate lesson of the Soul Urge is that life is a marathon, not a sprint. It’s funny because most people want to have Master Numbers in their chart, thinking the Master Number is superior to a “regular” number. But this is just not so…. A Master Number indicates that before incarnating, you opted into this lifetime on Earth with higher potential, yet with more intense challenges. These challenges will often manifest as life-long feelings of internal (and sometimes external) nervous tension, feelings that you’re never doing enough, being enough, doing it right, or living up to your potential.",

  "Yet those with Master Numbers are the ones being called upon to step up and take the lead in some fashion, to think bigger, and to make a mark, so it’s not an easy road. So if you’re working through life with a Master Number, don’t expect it to be easy … And if you’ve yet to decode your personal numerology chart, be careful what you wish for! There’s an undeniable intensity related to carrying the Master vibration, so it’s extremely important to know how to optimize and manage it, so you don’t crash-and-burn. Attempting to shine too brightly too rapidly, or suppressing, sublimating or ignoring your mission can both be painful routes to self-sabotage, and need to be avoided. There’s an undeniable intensity related to carrying the Master vibration with you and therefore extremely important to know how to optimize and manage it so you don’t succumb to the “crash-and-burn” that can result when you attempt to shine too brightly, too rapidly – or the self-destruction that can result when you’re avoiding or sublimating your mission.",

  "For you with a 22/4 Soul Urge, it means that the foundational energy of your soul’s desires aligns with the archetypes of the number 4. You are the ultimate teacher, a developer of strong systems, and a purveyor of hard work, while always managing to meet clearly defined goals. But in addition to this, you contain the master number powers of the 2, in double intensity! It’s as though you’re a Siamese twin and your twin is the Yang to your Yin. The 2 is all about diplomacy, patience and love, and is highly emotionally sensitive; while the 4 is all about gathering knowledge, and building and maintaining the systems and foundations which keep life contained.",

  "As Numerologist Glynis McCant’s observes, the 2 and the 4 are “business” numbers: The 2 is in the business of love and relationship and the 4 is in the business of security and stability. Whilst the energy of the 4 is most related to limitation and feels safe and comfortable with rules, often seeing things as “black or white”; while the energy of the 2 is most directly related to the emotions and focuses first and foremost on the needs of others. So can you see how there might be a few issues along the way!?",

  "Many numerologists will say that the Master Number 22 is the most powerful force in Numerology. Its energy carries with it a potent ability to manifest great things, yet the requirements for success are focused goals, organization, and doggedly following step-by-step processes. It’s vital to understand that this isn’t “slapdash” sort of energy. The Soul Urge brings the frequency of the slow and steady progress needed to build something solid, tangible, and useful.The Soul Urge 22 comes to work early and goes to bed late (metaphorically speaking). If you expect this to be a light frolic and an easy time, you’ll be in for a shock! Yet this is the energy that your soul chose for you to work with, in this lifetime. If you can nurture the expectation of core feelings of satisfaction and purpose, whilst taking the time, energy and planning to get from point A to point Z, then you’ll be using this powerful energy optimally.",

  "You’re at your optimum when recognizing and blazing through limitations – both external limitations and limitations that are self-imposed. This Soul Urge number is a powerful one, demanding that you learn how to focus and manifest in the practical world. This is important: Without bringing your grand ideas to actuality, and expressing your personal breakthroughs by actually building something real in the world, you are not truly fulfilling your potential. Almost, but not quite.
  Your real gift comes in being an example to others and teaching through what you do. The very best way you can teach and uplift others is by example.",

  "Your compatibility in relationships will depend very much upon your partner’s patience, care and ability to understand your need for a secure, committed foundation as well as your need to be out there doing good in the world. As a highly loyal and exceptionally trustworthy partner, you expect the same in return. But your potentially turbulant path through life means that you may not be always able to give as much time and energy into personal relationships as you would like.
  Hence needing an understanding partner. Because of this, you may find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher.The numbers you have most compatibility with are the 2, 4, 6 and the 22.
  The numbers you have least compatibility with (though the ones where you have most to learn) are the 3 and 5.",

  "Know that your 22/4 Soul Urge is a profound journey that offers you multifaceted opportunities to create a solid, steady, and stable home environment while also creating things of lasting value in the world. Whether that’s by using your teaching and knowledge skills or creating actual products, what you do with your life will go on to benefit people’s everyday lives. At your core, you’re a spiritual guide who is highly intuitive and also imminently practical. With the 22/4 as your Soul Urge, this might be something only you can see or feel. Or alternately, you may tap into your masterful teaching, embrace your heightened ability to work hard to achieve goals; and make positive use of your super-charged spirituality in a substantial way. It ultimately depends on the other numbers in your chart and how those energies mix and match with your inspired and spiritually focused number 22/4."
  ]
  elsif self.number == 33
  [
  "You have a deep need to bring an elevated form of loving service to the world. When you look deep into your soul, you have an underlying and pressing need to evolve spiritually – no matter how you define it. Yet here’s the catch. With the Master Number 33, you’ve got your work cut out for you. It’s beneficial to understand that this will truly take a lifetime of development, so pace yourself. Your heart’s desire requires deeply felt experience and tests you over and over again. This Soul Urge is a marathon, not a sprint. It’s funny, because most people want to have Master Numbers in their chart, thinking the Master Number is superior to a “regular” number. This is just not so. Yet let me explain: The Master Numbers indicate that you opted into this lifetime with higher potential, yet also with more intense challenges. So honestly, when you’re working with a Master Number, it ain’t easy. So be careful what you wish for! This translates into life-long feelings of internal (and sometimes external) nervous tension, feelings that you’re never doing enough, being enough, doing it right, or living up to your potential.",

  "And those with Master Numbers are always being called upon to step up and take the lead in some fashion, to think bigger, and to make a mark. There’s an undeniable intensity related to carrying the Master vibration with you and therefore extremely important to know how to optimize and manage it so you don’t succumb to the “crash-and-burn” that can result when you attempt to shine too brightly, too rapidly – or the self-destruction that can result when you’re avoiding or sublimating your mission.",

  "Yet the basic foundation it needs can take literally years of trial-and-error to form the basis from which to build, and then act. It is your deepest and fondest desire with a 33/6 Soul Urge to act upon a deep sense of joyful loving service – and to use your heightened creativity and love of beauty to the fullest. And you wrap it all up with a super-responsible bow!",

  "The Master Numbers are innately in conflict with themselves. What does this mean? For you with a 33/6 Soul Urge, it means that the foundation of your deep desire resides with the energy of the number 6. You’re the nurturer – the magnetic visionary, justice seeker, and master or mistress of the domestic realm. Yet then you must add on the double 3. It’s as though you’re a Siamese twin and your twin is the Yang to your Yin. The 3 is all about creative self-expression, communication, optimism, and emotional sensitivity. You crave creativity and connection. The 33/6 is a rather enigmatic calling. It’s as though your soul is asking you to elevate your thoughts and actions into the “Mother Teresa” realm while also being dynamic, creative, and joyful in the process. So try that on for size!",

  "Can you see how there might be a few issues along the way? It’s a constant push/pull between wanting to be of service and help and heal others – and yet you might also find that your perfectionism and judgment of others get in the way. The Master number is asking you to commit – to step into the spotlight, into leadership positions, and trust in your ability to provide joyful and helpful service to a larger audience in whatever form you choose. It’s a constant wrestle with letting go of self-righteousness and control while infusing love and service into all you do. You’re perpetually riding the teeter-totter of “I want to heal the world” and “The world doesn’t deserve what I have to give.” Master Number 33 is the conduit of joyful, loving, and nurturing service. Yet you can easily tip into the martyr role. Rather than being helpful you can opt for meddling. Rather than loving you can judge harshly and critically. Understand that “Master” actually means “Teacher,” not someone who’s superior, the boss, or a slave driver! As a 33, your basic “Master Number 33 Soul Urge 101” Class is to master self-care. You must learn to know and love yourself first before you can extend your gift of love and service to others.",

  "In relationships, you can likely swing from being highly attentive and affectionate with your partner, to needing your own space. You are naturally empathetic, so good boundaries are key (as is a partner who respects them). The underlying frequency of the 6 means that family is hugely important to you, in fact you are devoted to the! Yet you must also take enough time to nurture your own creativity. So it’s vital that you have a partner who understands this, lest your energy levels become depleted. It’s likely that you will experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a master teacher. The numbers you have the most compatibility with are the 3, 4, and the 9. The numbers you have least compatibility with (though the ones where you have most to learn) are the 1 and 8.",

  "Know that your 33/6 Soul Urge is a profound journey that offers multifaceted opportunities to inspire people with your joyful service and creativity – whether that’s by acting, music, medicine, counseling, being a homemaker or any other creative endeavors. At your core, you’re a selfless spiritual guide who is highly intuitive and infinitely loving. With the 33/6 as your Soul Urge, this might be something only you can see or feel. Or perhaps you easily tap into your nurturing disposition, emotional self-expression, and service? Making positive use of your super-charged spirituality could already make up a substantial part of your life. It ultimately depends on the other numbers in your chart and how those energies mix and match with your responsible and nurturing number 33/6. Understand that – like all aspects of Numerology – the higher aspects of this number are a goal. It can often feel like an underlying drive that you can’t explain – even to yourself. Yet it’s good to be aware that you’ll likely experience more focused and intense challenges on the path to mastery."
  ]
    end
  end
  end

end
