class Expression < ApplicationRecord
  has_many :charts
  has_many :users, through: :charts

  def short_description

     if self.number == 1
  "Number 1 as an Expression number is a symbol of inborn leader. Your life will be oriented on development, freedom (so it is important for you to be financially and personally independent), constructing your life plan. Your name can be useful for you during your life, and help you reach high step on a professional ladder. You obtain strong power of will, and it should be used and directed on your goals. Try to use every possibility you have. The critical mind and ability to broad analysis that you have are the keys to your success."
    elsif self.number == 2
  "Working with others is your forte. Your 2 Expression makes you very skilled in relationships of all kinds, because it is cooperative, supportive, and always striving for balance. You have a keen ability to read people and situations and react with patience and understanding. Others see you as peaceful and humble, yet there is great strength in you. Still, your feelings can be easily hurt and you have a tendency to doubt yourself when making decisions, which can make you idle. You would benefit from following your head instead of your heart from time to time."
    elsif self.number == 3
  "With the influence of the number 3, you are a naturally skilled communicator. You have a way with words and a great talent for conveying your creative ideas and inspiring others. Your social circle is strong and people find your optimistic attitude both magnetic and charming. However, the relationships you form, like many other things in your life, don't go very deep. Your enthusiasm for life can be a distraction, making you unable to stay focused on one person, job, or plan long enough for it to develop into something complete or meaningful."
    elsif self.number == 4
  "Organized, down-to-earth, and hardworking, the 4 Expression gives you skills that make you incredibly capable and constructive. You are a master at managing projects and teams and others rely on you because you follow everything through to completion. You are honest, patient, and loyal -- sometimes, loyal to a fault. The number 4 carries a stubborn, rigid energy that can make you so fixed in your ways that you are unable to grasp new, better ways of thinking, doing, and interacting."
    elsif self.number == 5
  "Your 5 Expression craves variety and freedom and wants to experience everything that life has to offer. You are an adventurous person who takes pleasure in trying new things and following your latest passion. Your passions change quickly, however, so you've learned to switch gears easily in order to explore as many possibilities as you can. Beware, though, that with all this change comes inconsistency. Your restlessness can make you unreliable in relationships and unprepared to handle the hardships of life."
    elsif self.number == 6
  "Your strengths play out most notably in your relationships with others. The influence of the number 6 makes you incredibly protective and nurturing toward all people, but especially your family members and other close loved ones. You have a heart of gold and feel a responsibility to be there to help those in need of support. It's important, though, that you don't forget about self-care. You can be so focused on the well-being of others that you neglect to attend to your own emotions and energy levels. Be kind to yourself, too."
    elsif self.number == 7
  "You are the truth seeker. You are energized by information and willing to go deep into both the intellectual and spiritual realms in search of real meaning. Logic drives the way you think and communicate, and this helps you clearly convey your vast knowledge to others. You are not satisfied with what's on the surface -- it's the hidden answers you are digging for. However, this assumption that there is always something to be found can make you suspicious of others. In fact, it may be hard for you to relate to other people in general; you tend to prefer a controlled environment where you can do things your own way."
    elsif self.number == 8
  "An 8 Expression blesses you with great business sense and excellent judgement of people, money, and plans. This is why you are able to achieve so many goals -- you know the best resources and the most attainable ambitions. You do run the risk of being too ambitious, however, and turning from an effective leader into an impatient taskmaster. While your drive to attain success and material wealth is powerful, it's important that you balance it with meaningful people, emotions, and experiences."
    elsif self.number == 9
  "Your 9 Expression is creative and compassionate and encourages you to find the best in everybody. Whether you're providing emotional support to a friend or engaged in a larger humanitarian effort, you strive to make life better for others. People see you as being friendly and affectionate, as long as you are immersing yourself in this altruistic work. If you are not living life in a way that is beneficial to other people, you could become self-centered and detached from important emotions."
    elsif self.number == 11
  "Having a Master Number 11 as your Expression blesses you with profound intuitive capabilities and an idealistic vision. You are driven by instinct and inspiration which give you a great, clear picture of the way things should be, yet you may lack the practical, organized thinking needed to bring your dreams to fruition. Still, your charismatic presence draws many people toward you who are in search of support, encouragement, and wisdom. You are a beacon of hope and light to those in need."
    elsif self.number == 22
  "Profound potential comes with a Master Number 22 Expression, which gives you a lot to live up to. In Numerology, this number is called the #{"Master Builder"} because it is capable of constructing grand ideas and even grander realities. You are a cooperative team leader with a unique approach to solving problems and a desire to help others. You are headstrong and driven, yet this brings a risk of becoming so domineering that you lose the support of others. Remember that your goal is to create, not to destroy. You are in total control of your destiny."
    elsif self.number == 33
  "If your Expression is the Master Number 33, your mind and heart come together to make you an uplifting source of hope and healing. You have keen insight into the ways the world works, plus the creative communication skills to share this knowledge with humanity. Others turn to you to help guide them toward truth and inner knowledge -- you are an example of experience and enlightenment. Though it may often feel like you are burdened by other people's struggles, realize that you have been given these nurturing skills as a gift, and give of them freely."
    end

  end

  def long_description

    if self.number == 1
  [
  "With a 1 Expression number, you possess strong leadership capabilities and a knack for creating your own opportunities. You will go where others are afraid to go and you'll make the journey look easy. The number 1's energy is extremely self-sufficient, allowing you to be most innovative and productive when you're working alone. You may even find it difficult to cooperate with others, preferring to do things your way rather than listening to anyone else's opinions. If you aren't careful, the 1 Expression could make you seem aggressive and self-centered. It's not in your nature to think before you speak or act, but you would be wise to learn this skill!",

  "Pay attention to your Life Path number, it may turn out that you need a mentor or a guider, if you need a help - ask for it. However, in most cases you are a person that leads and shares the knowledge and experience with others. You are an authority and inspiration for some people around. You easily sort out the details and are stress-resistant in important moments, though your emotions take over sometimes. It is very important for you to implement you skills and express your professional ability in your career. You should put all your strength now to realize your potential in the future. Always search for different possibilities to present the innovative ideas you have. Your life is like well-thought strategy where you are always on the step ahead. People with your disposition are usually favored by the Universe: they own a business, run a company and are independent and self-sufficient. You strongly believe that hard work and efforts can help to break through. When you are mature enough, you will have to know already what you want from life and what are your main desires. The other important aspect is confidence. No one but you is responsible for your success, and you need to be sure that you'll succeed, as things will be as you believe them to be. You are ambitious and curious person, sometimes it seems like you can't spend a calm week. However, you easily lose interest. Also, the other side of the confidence is self-assurance that is manifested by narrow mindedness and stubbornness.",

  "Ones are known for their patience and persistence. They are happy, materialistic, driven, clever, attractive, independent, sincere, focused, logical and intelligent. Since ones are fruitful in life, they should couple these qualities with a sense of humor. Maintaining the ability to relate to others through humor keeps them grounded, and allows ones to avoid egocentricity and superiority. Mistakes are rare, but when they do happen, it causes ones extreme frustration. However, errors can be a helpful dose of reality to combat self-centeredness that often accompanies success.",

  "With maturity, ones only get more ambitious and determined. Their drive, focus and ambition that expression number 1 people posses mean they will excel in positions of power. They will likely be CEOs, entrepreneurs, executives or promoter. They are problem solvers that are quick to act. These qualities bode well in positions of importance. A one’s purpose in life is to solve problems. Issues involving the environment and psychology allow them to thrive and make the greatest differences in the world around them. However, they are fiercely independent. They do not work well within a group because they will thwart others.",

  "Their aggressive nature makes them difficult to live with. People possessing a expression number one aren’t what you’d consider romantics, but are very loyal in marriage. Ones desire companionship and will often have many relationships before settling down. This is a direct result of having overly high expectations of their mates. They tend to be single-minded, often focusing solely on their careers because they thrive on success that is quantifiable. They expect praise and encouragement from their mates, but often don’t reciprocate those acts. Their relationships get thrown on the backburner because their immense desire to be successful professionally.",

  "This  expression number is associated with excellent health and spiritual wellness. Ones are considered to be lucky and clairvoyant.",

  "Since ones frequently spend their life in a position of power, they can have very large egos and appear pushy. If a one loses their humility they can become incorrigible and self-destructive. Their hunger for success can result in unachievable goals, and this can lead to frustration as well as low-self esteem. A one’s fear of being “caught in a rut” makes them quick to jump the gun to avoid a monotonous lifestyle. Their aggressive and domineering nature has the tendency to make them difficult to relate to, which means they will appear self-centered and egotistical. Creating a tactical plan can help ones to achieve goals without the need for excessive forcefulness. Learning to manage a balance is vital to maintain relationships."
  ]

    elsif self.number == 2

  [
  "Number 2 as an Expression number shows that sociability and interrelationships will play major role in your life. The letters of your name create a combination that in refers to the person who is able to understand people deeply and comfort them in times of trouble. You can make a great psychotherapist, peacemaker or diplomatic worker. Through the years, you can find yourself to be skillful in eloquence and especially delicate when it comes to interrelationships. Number 2 that also corresponds to master number 11 (2) is a very strong number. People under such number are inspirational and easily encourage others on important decisions. The inner power you have makes you a gifted tutor, philosopher, consultant, social activist, diplomat, and worker in any rescue center. No matter what career path you choose, you are skillful professional that inspires people around. You are very sensitive to the surrounding world and it reflects on your intuition: it is well-developed.",

  "You are a good team player, but bad lone player. Working in a team you guide others and express yourself this way and it is a reason of your success. Boost your self-confidence in order to become more independent from social opinion, and feel more secure by yourself. Injustice is often in our world, and a lot of people will be rewarded for your ideas and input, but don't worry, you express yourself in team, so just do what you do best. Your principles and ideas are more important than social appraisal. After you've become more confident, people will be magnetized by your change, so take your chance to establish your life the way you want it. You have mature set of principles to which you adhere, and it is great, because principal people are solid in their beliefs and confident in their mind and skills.",

  "However, the other side of number 2 is oversensitivity. That is why you need to boost your confidence, so you are more protected from social triggers that can hurt your delicate soul. It is normal to be sensitive, but in our world some protection mechanisms are needed. If you have many 2's in your chart it may cause you to be lazy and apathetic to the world around. In some cases, number 2 (especially derived from master number 11) suffer from uneasiness and overemotional reactions. Try to keep balance in everything you do. You are a dreamer, and you often prefer dreams to grey realities. Be careful and try to make decisions with a clear mind and precise wants from life.",

  "Twos are gentle, diplomatic, adaptive, calm, sensitive, considerate, emotional, detailed and balanced. They are socially intuitive and supportive. Their friendly nature helps others to feel comfortable around them, and they despise arguments. Their gentle nature makes them overly sensitive in disagreements, and twos will experience low self-esteem in relationships that involve a lot of arguing. They’re keenly aware of the needs of the people around them, which means friends are never in short supply. Twos find that the nicer things in life are necessity, but they also value the small, kind gestures of others. They have an artistic vigor, and later in life they’ll find comfort in meditation and the outdoors. Twos generally have excellent self-esteem, and strictly follow the golden rule, which makes friends easy to come by. Positive life circumstances will allow them to grow and shine. The same qualities that make twos excellent at negotiating can also make them appear weak, submissive and indifferent. They fear quarreling and unplanned changes, as well as being alone and making errors.",

  "People with the  expression number two are lovers of the arts, and that naturally makes them excellent actors, dancers, poets or writers. Since twos are also nurturing and selfless, they will excel in the healthcare field. Jobs like nursing, psychiatry, social work, teaching and doctoring are positions that fit twos well. Career choices and voluntary pursuits that benefit others put twos in a position to prosper.Since quarreling doesn’t bode well for people with these destiny numbers, any job involving a competitive working atmosphere will be uncomfortable.",

  "Expression number 2 loves deeply, intimately and effortlessly. A partner that doesn’t appreciate a two’s kind and nurturing nature will take advantage of them. However, being in a relationship with a person who is too dependent will end in failure, too. If they are wronged twos will often promise not to love again, but these feelings subside quickly. It has been reported that twos often have issues with mental wellbeing. They’re indecisiveness can often cloud their mind and make them disillusioned. Reality and fantasy merge and they becoming unreasonable, which results in mental unbalance. Twos that are overly sensitive struggle with nervous tension, too.",

  "Since nurturing and keeping the peace are integral parts of a twos psyche, maintaining patience, balance and tolerance is important to their overall happiness. Being true to their inner calling is important to remember, but not at the sake of losing themselves. Because they are often so focused on others, they put their own needs and desires on the backburner. Learning to balance the scale is vital in order to live a happy, stable and fulfilling life."
  ]

    elsif self.number == 3

  [
  "People born with expression number three are built for arduous work. Their strong bodies are built to maintain the pressures around them, and they’ll likely test that theory frequently during their lifetime. They’re born lucky, which saves them from being involved in accidents and falling short financially. Threes are multi-talented, creative, energetic and artistic, and they will grow creatively and spiritually throughout life.",

  "Expression number 3 means that your life is closely connected with creativity and artistic expression. Number 3 implies developed power of will, ability to self-analysis and acceptance of criticism. You need to be ready to be on stage and provide positive emotions for your audience. People with this number are so energetic that why are we still searching for the source of eternal energy, when we have threes. The main role for you to play in your life is to inspire people around, to make small things that mean a lot, or to influence from the large stage to the audience. People with Expression number 3 can make brilliant artists, actors, musicians, teachers, singers, and dancers. No matter what profession you choose to live by, you will always be interested in artistic expression.",

  "The creativity of your mind can be manifested in professions connected with analyzing of needs and desires of people. Marketing and promotion are spheres friendly to you. With your charm you can make a person buy or pay attention to any product or company of your interest. Develop these skills, and you'll see how drastically your life can change. It is a pleasure to hear you talking about sphere of your interest, because you automatically make it so attractive that people around can hardly pass by. Due to your level of energy and wit of mind you can support many topics and make reasonable statements if it comes to arguing. Inspiration for you is a key to everything. When you are inspired you are motivated to act, and it always brings you profit. Keep closer to your friends. Despite your character and talkativeness you don't have many true friends, so if you have that one friend it is valuable. Also, learn to be a friend in return. Through years, when your mission is understandable for you, you will become more social and open. The only essential shortcoming of this number is inability to concentrate on one thing for a long time, so all the efforts you've done before are in vain when you quit it.",

  "Threes are imaginative, responsible, talented, outspoken, optimistic, good-natured, generous, loyal and charming. Their energetic nature and stamina allow them to maintain large workloads and pressure. Threes are born leaders, but they don’t frequently seek the limelight. Their leadership instincts and dedication to their career help threes excel in handling extreme work stressors. They also have a magnetic charm, which means they constantly make new friends and supporters. Threes are excellent conversationalists. Their love for life encourages, motives and inspires others. Threes are foodies who enjoy the comforts of home. It is possible for a three to spread themselves too thin. Keeping and maintaining friendships are of the utmost importance to threes, but they should not waste time worrying over trivial things. Their self-sacrificing nature can hinder their growth, and their drive to be financially successful might make them appear superficial. It is possible to develop an addictive personality if money is spent wastefully.",

  "People with  expression number three will earn money through different ventures during life. Their leadership skills, charm and work ethic make them popular and well suited for politics. Threes are also predisposed to excel in fields like business, sales, education, religion, advertising, publishing and tourism. Their giving nature will lead them to philanthropic endeavors later in life. They take pride in working hard to help others. Threes also have a love for the arts, but only a few will select a field that puts them on stage.",

  "People with expression number 3 not only have great friendships, but they also have a strong family bond. Their charm makes them an exciting lover, but they can lose interest quickly if their mate becomes boring. A weakness for sex may make them unlucky in love. This weakness may also cause various affairs. A three’s partner will devote all their time toward creating domestic balance. Thus, the three can spend ample time working on their career. Since a three’s career and life will likely be spent in the company of others less fortunate, they must develop a compassionate nature. They must seek a clearer understanding of others to be fruitful. Coupled with clarity, a three must also capture the ability to be a true friend. Keeping and maintain friendships will be a huge part of a three’s life, and success will only be gained after learning the true value of companionship. Since money will flow easily from multiple sources for most people with  expression number three, they must learn to avoid overindulgence. Threes should fight the urge to be wasteful, and instead learn to live in moderation. Becoming monetarily over excessive will lead to an addictive nature and financial hardships."

  ]

    elsif self.number == 4
  [
  "Number 4 as an Expression number shows that your life is oriented on the career, leadership, sense of order and justice. Through the years you will become more pragmatic, realistic, skilled in your professional area and detail-oriented. You are a perfectionist in some way, and it will be reflected on your work so everything is done brilliantly or never done. You have a lot of future possibilities to succeed in spheres of exact sciences if you are keen on details. You can make a nice teacher, but also in spheres of crafts and exact sciences, because you are easygoing and ready to share the knowledge you are master at. Even if you are an artistic nature, your art is technologically oriented or well and precisely thought. Try yourself in interior design and planning, in landscape design, graphic design and architecture. By the way, many skillful surgeons have number 4 as an Expression number. You can easily work at any field where arrangement, calculation, management and precise estimation are needed.",

  "People with number 4 are usually very initiative, especially if number 2 comes from master number 22. They are skillful entrepreneurs and love to make their job done on the highest level. They also love to hear compliments regarding their professional achievements, because it compliments not the beauty that is given naturally, but the achievements that are gotten by efforts. It is hard to be your friend, because you search for the best in people and demand best from yourself. Such high standards are rare nowadays. You are very principled and critically estimate information that comes from other people. You can make friends with people of high moral standards and witty disposition.",

  "People with  expression number four often work as the stabilizer. They are cerebral beings that worship order, organization, management, discipline, routine and rules. Fours can easily take on difficult or unpleasant tasks because their desire to share wisdom and knowledge. They are extroverts that work well alone and with others. Success is quantifiable by comprehension and wisdom earned. They have a huge appreciation for their home and they seek security.",

  "People with  expression number four are organized, patient, dignified, dependable, honest, devoted, determined, loyal and hardworking. They hold true to traditional values and appreciate order and having a system. This number is ruled by a cerebral power, and they thrive when they are putting new ideas in order. A four will work steady toward any goal with a detailed plan. They are productive, hard workers and remain neutral in most situations. Their extroverted nature works in tandem with their strong moral compass. The combination allows this person to be easily relatable and harmonious.They consider creating a foundation their duty. The base they construct is often built from patience and perseverance. They value security and work to protect themselves and others. Because of their need for order, they lack the ability to adapt to new situations. They’ll frequently miss out on excellent prospects because they dislike change. They’re homebodies so they can become prone to laziness.",

  "Expression number 4 people are inclined to make money in a variety of ways, but they will also spend wastefully. They are often work-oriented because they always have a plan of attack. A four’s need for structure bodes well in managerial and HR positions. They are realists that value honesty. They’re also highly intelligent and analytical. Careers in fields like engineering, production, computer science, mathematics and astronomy are also an excellent fit for a four. A person that has a  expression number four considers their home their sanctuary. Fours value a strong family support system, and they will maintain loyal to their partner and family. Sharing the simple pleasures in life with a supportive family gives them great pleasure and balance.",

  "There are several areas where a four must learn flexibility to reach their full potential. A four must learn to maintain balance when adjust to change. They often get so set in their ways that a slight deviation will cause them to detest their life. Fours need time to adjust to things methodically, but this can appear to others as uncompromising. They can become argumentative and aggressive if they’re patience is pushed. Their active minds make them doubtful. When meeting new people or being thrust into unknown terrain, they will become suspicious and pull back into their shell. This factor will cause them to miss many fulfilling opportunities throughout life. A four thrives on acknowledgement, but they don’t often get it. Their work will suffer immensely, often never getting finished. Without praise, a four will never find satisfaction in their work life, and this leads them to change professions frequently."
  ]
  elsif self.number == 5

  [

  "People born with  expression number five sit in the middle of the destiny numbers. They are flexible, and desire the freedom to act when they deem fit. They are non-conventional will not be tied down. Fives will see and experience more than any other vibration in numerology. Their curiosity and need for change will encourage many adventures, experiences and opportunities.",

  "Number 5 is a sign of activeness, desire to change and to be always in the center of events, creativity and independence. Those who have number 5 as their Expression number are really lucky, as they pass through many lucky possibilities in their life. To extract the best features of your number you will have to learn to set priorities, to concentrate on needed things and to use your time in a right way. You will have a freedom of choice, and when time comes you need to make a proper one. You will have to become flexible and fit into different situations. Through years you will learn how to use your charisma with profit, in other words you will be able to manipulate people, to make them adhere to your position. It is especially useful if you chose a profession where you need to persuade people to buy something. You are intellectual and think and react quickly regardless of situation.",

  "Hold on for innovations, you will have a lot of possibilities if you attentively follow trends and react on them. You need to catch the right wave and you will become successful and will be able to express yourself fully. It is natural for you to be curious and innovative. You are always surrounded by people, because you are a great listener and you can easily imagine yourself in someone's shoes, it is your kind of intuition. This number is great for many career choices, as you are intelligent and easy to teach. Look closer to work directly with people, because you know how to cooperate and persuade them. Advertising, radio and television, journalism, psychotherapist, and business management are the fields where you have a lot of chances to succeed. You are a competitor, you need new emotions and new goals quite often, so it is normal for you to change working places.",

  "If 5s appear frequently in your chart some negative features of number 5 may be present. You are very changing person. A lot depends on your mood, so you need to learn to cool your temper sometimes. Also you tend to scatter on so many things at one time that you rarely finish something. It may be useful for you to become more disciplined if you want to reach particular goal. Try to avoid prejudices and superficial thinking.",

  "A five sees every opportunity as an ability to grow, and will often become independent at an early age. They are opportunistic, curious, energetic, persuasive, outgoing, charming, imaginative, intellectual, unconventional and fun. Having a routine is like being imprisoned for a five. They desire the freedom to do, say and experience things as they see fit, and will only thrive in these conditions. They enjoy impulsiveness and pleasure, and this often leads to over-indulging. Fives will express themselves in unique ways, and they do not follow the status quo. These people are eager to adapt and welcome change. An unwavering curiosity will cause them to start one task and quickly switch gears to something else. They love the arts, travel, sports and new places and things. Often playful, witty, energetic and fun, a five enjoys casual flirting and is always the life of the party. They thrive being the center of attention. If a five feels tied down, they’ll often stir up trouble to fill the void. Since they detest routine, learning to adjust to general responsibilities will make this person unhappy and uncomfortable.",

  "Since expression number 5 people hate to be tied down, work is considered a means to an end for fives. They constantly seek freedom, and will not feel a commitment to their workplace is important. They are not inclined to tackle work-related problems. Instead, they’ll move on to another job. Fives are capable of solving almost any problem on their own because of their independent nature. This quality makes them excellent journalists, teachers, freelancers, writers, judges, politicians, speakers, artists or business people.Their curious and adventurous spirit makes many fives pioneers. Their quick and sometimes irrational decision-making works well in fields like exploring and inventing.",

  "People with the  expression number five have difficulties settling down. Their fear of confinement often causes them to discard things and people quickly. Their need for constant change and transition means they have many friends, but very few good ones. Smothering relationships, in any form, do not work for fives. They’ll have numerous relationships because they have many admirers. To make a relationship work a mate must learn to accept the five’s impulsiveness nature and desire for freedom. A five is happy to share the good things in life, and the relationship is often a happy and harmonious one. A declaration of love, which doesn’t come often, is an indication of their desire for commitment. A five must strive to rein in their impulsive nature. Because they’re quick decision makers, they do not weight and measure the consequences for their actions. This characteristic often ends up hurting others."

  ]

  elsif self.number == 6

  [

  "Expression number 6 is usually associated with family values, kindness, love, responsibility and openheartedness. Through the years you will be experienced in communication with people. You will be especially concerned about those, who weren't lucky enough in this life. You will be skilled in problem-solving and ready o give an advice to anyone who needs it. It is in your nature to work with and help people. You can make a great parent. You are caring, loving and soft person, though you have strong character and you are hard to stop when you've planned something. You are empathetic and nice to talk to. You are honest, but not rude, such type of harmony is rare. You love comfort and you feel comfortable only at home, where you are relaxed and surrounded by close people. It is obvious that you are a nice friend, you accept people for who they are without judging.",

  "Number 6 is often a sign for wealth. You are artistic person and need some artistic expression, but your career path would probably be connected with another sphere. You can express yourself best by communicating and helping others. It is your mission in life, because you care, because it is important to be less selfish in our world. Number 6 are great teachers, psychologists, doctors, firefighters, social workers, and consultants. Such people are interested in design and decoration, because they like to be surrounded by beauty. Some negative features are also present in number 6, especially if there are a lot of repeated 6s in the chart. Sometimes people with number 6 care too much so that they are annoying or disturbing others. In other cases such people are obsessed with control, so everything is perfect. They often forget that the notion of #{"perfection"} is different for people. You need to learn to accept criticism with dignity, without lowering your self-esteem because of someone's opinion.",

  "People born with the  expression number six are caring, protecting, graceful, loving, charitable, nurturing, balanced, reliable, compromising, faithful and honest. They are often too self-sacrificing, and will never expect any payment or acknowledgement for their actions. Because of their instinctual need to help others and their trusting nature, they’re often taken advantage of and can be a terrible judge of character. They’re well-liked for their warm, friendly personality. Sixes will always favor the underdog and are eager to right wrongs, even if that means being a bit of a perfectionist. If a six becomes too focused on rectifying smaller issues, they can lose sight of the bigger picture. Their infatuation with seeking truth can come off to others as slightly self-righteous. Often considered the most harmonious among all the destiny numbers, if a six falls into emotional of physical conflict, they can become the most destructive of all the numbers. A person with this number loves to teach and guide, and will likely take on a role as a caregiver to the young, old, handicapped or less fortunate. This person can always be held accountable for their fair share. They’re willing to contribute their part, plus some.",

  "Expression number 6 people will thrive in a position that allowed them to flex their negotiating muscles, but not in a competitive arena. A person with the  expression number six will excel in the arts, promoting, fashion or beauty. Their love for people and the less fortunate can also lead them to careers in community service, ministry, counseling, law enforcement, nursing or teaching. A six must remember to create standards that can be met. Their predilection for setting goals too high comes off demanding and can cause them to be over critical of themselves. Sixes must learn to take things at face value. Developing this skill will allow them to avoid getting too attached to people before they show their true colors.",

  "A six is driven by love, and considering their attractiveness and sex appeal; they have no issue finding people to flirt with. Sixes dislike living alone and believe that all domestic relationships are meaningful, but often find seeking a mate difficult. People with other destiny numbers are often dissuaded by their looks, and a six is often a terrible judge of character. They aren’t usually comfortable displaying affection frequently because they fear rejection. Sixes have deep-rooted anxiety and insecurities, and this can often result in a variety of phobias. They obsess over little details, which can also cause OCD."

  ]

  elsif self.number == 7

  [
  "People born with the  expression number seven are wise, warm and compassionate. They can easily weigh and measure the elements of a situation to reach a rational approach that works best for everyone. However, they often underestimate their skills. They have analytical minds and a thirst for knowledge, but they usually prefer working alone, though they have many admirers. Throughout life, sevens will get in touch with a more spiritual and mystical side of the world. Many sevens can even develop clairvoyance or other psychological gifts.",

  "Number 7 as an Expression number shows an analytic, pragmatic and intellectual person. You are direct and honest, so you demand it from people around. You can make a great judge or journalist. You are very attentive and curious that in combination with analytical skills makes you understand things profoundly. Though you see more, you never try to disturb others or violate their privacy. Your curiosity and sense of justice let you seek for information that is important for everyone, especially if it is hidden. You always see more than others, so you are on one step ahead in every situation. If you are keen about something, you will become almost a professional in it, because you will start to read, to learn more and to investigate. You can be a teacher that changes lives of the students, as you are so inspirational and energetic that it is hardly to find someone better for guiding people.",

  "You are a weirdo for some people just because they can only guess what you are thinking about. During your life you can be identified as friendly and positive person in harmony with yourself and the world. You care about your privacy and don't want strangers in your life. This number has pleasant positive features. You like logical order in everything, so you always know where you can find anything at your house, the same is about the structure of your mind, as you have logical associations with things you need to remember. However, you can be too logical and rational that you protect yourself from emotions, even if you deprive yourself of something good. If you have a lot of 7s in your chart it may be manifested through lack of trust to other people and emotional estrangement. Due to such aloofness you can be an introvert in the most negative meaning of this word, you may be alone as a result and feel lack of warm communication.",

  "Sevens are warm, understanding, sympathetic, adaptable, happy, imaginative, witty, intelligent, charming, eclectic, sweet and humble. People born of this  expression number are always in search of a deeper understanding of life. Though, their constant curiosity and search for information can be a good thing, it does make sevens question even good things in life. They must learn to take things at face value. Sevens have a very large circle of friends. Their ideas and personality, though eclectic and deep, are magnetic. People with  expression number seven are expert conversationalists that are young, alive and sharp. Their decisions are always backed with methodical thinking, but sevens are considered unpredictable.",

  "Sevens will likely be found working in a place where they feel they’re benefiting the world around them. They’re not driven by material wealth, but instead, by concepts, knowledge and ambition. Their independence and honesty make them valuable additions to any workplace. Because of a seven’s keen ability to relate facts and balance situations, they make excellent peacemakers, spiritual leaders or judges. Their love of cultivating knowledge leads many to academic fields, too. However, they also have a persuasive, quick-witted personality that allows them to excel as lawyers and debaters People who find that they belong to this expression number will also thrive in an environment where they can work in solitude. This work style is conducive to careers in science, research or libraries.",

  "Sevens are romantics, and they are eager to express love in a variety of different ways. They will often declare their feelings too early, which cause the object of their affection to feel that things are moving too quickly. They balance well with, and often attract, people who have difficulty showing affection. These matches normally work well as long as the partner can learn to reciprocate and appreciate the sevens acts. If not, they will begin to feel insecure and pull away. There are a few negative characteristics associated with expression number 7. Because of their need for solidarity, they often become overly introverted. This can lead to being intolerant of certain situations and people. Also, their eagerness to love can become overbearing. A seven must learn to keep their emotions in check for the sake of growing relationships. This will allow them the time to learn if the relationship is of value or not. Pumping the breaks on new relationships will also help sevens protect their hearts. They must also learn to overcome past failed relationships to openly trust in new ones."
  ]

  elsif self.number == 8

  [

  "People with  expression number 8 are the authority figure in numerology. Eights are extroverted and self-disciplined. They take on positions as leaders and are incredibly goal driven, dominant, hardheaded and professional. They are often obsessed with work, and will dedicate their all to any undertaking. Eights are better at grasping tangible facts than emotions or ideas. This  expression number is associated with karma.",

  "Number 8 is usually a sing of people who are concerned about their material wellness. Number 8 can make a great business owner or entrepreneur as well as nice administrator or other leading position. You want to be in movement, to provide innovations and establish new tendencies. The reason for it is a financial success. You know value to your efforts, time and ideas. You are a person which authority is felt after the first meeting. You are a great chief and inspirational guider, especially if number 8 shows more positive features. The things that you do on the high level are promotion, providing innovation, introducing new technologies and presentation of your ideas. You are inborn leader and can create your own successful enterprise.",

  "You can become not only successful business owner, but also have essential governmental and administrative positions. You have skills enough to establish and support your own entrepreneurship and the fortune is on your side.You have financial instincts, and in your life you will get a financial reward. A lot of people can gain something, but you have capability to support it and not to lose everything in the commercial world. A big deal o your fortune is about your skill to judge a character. Having number 8 means ability to underst and people who are great to have common affairs with, and see people whom are better to avoid. You should be pragmatic and practical in your business decisions.",

  "Despite the business success, you are the right person for leading governmental positions, as you are responsible and have a strong character. You love and respect money, and such attitude makes you qualified enough to know how it works and how to reach financial success. You understand different financial schemes and mechanisms. Also you are suitable for commercial world with your strong power of will and purposefulness. You know what is good or bad for you just in the moment you see it, you are very keen. It gives you an advantage of choosing right people among those, who pass by you. You see person's true goals and intentions.",

  "You are self-confident, but not self-assured. Sometimes you lack of pragmatic point of view, because you may be overemotional about something. Stubbornness is the main thing to avoid, try to look at everything on a larger scale, take into account other opinions, and you will get the fairest result. If something goes wrong, you need to pull yourself together and never let emotions take over. When it comes to emotions, you'd better separate your business from your feelings, because both may be damaged. The keys to your success are determination and harmony.",

  "People born to  expression number eight are talented, dependable, self-reliant, pragmatic, professional, confident, powerful, organized and self-disciplined. They’re often the person you see leaving last at night and arriving first in the morning. Eights are driven and focused. They will work tirelessly to accomplish something they believe in because no task is too great for them. This means that they often leave a legacy for future generations. They execute complete control over projects and are often in positions of great power. Eights are risk-takers who are typically financially secure and business-minded. However, they must balance their physical wealth with spiritual stability. They don’t push ahead too quickly but instead believe that slow and steady wins the race. Eights have sound judgment, and the universal law guides them in everything they do. They are eager to help others, but must remember to delegate tasks as to not take on too much responsibility.",

  "People with the  expression number eight are strong-willed and ambitious. If success in their field is what they desire, they commit themselves wholly to their career. However, eights will straddle the correct balance between their social life and their job throughout their life. Eights will likely be in fields like finance or marketing. Because of their goal-driven nature, they’re also excellent entrepreneurs. They will excel as managers, presidents or CEOs, too.Relationships are an absolute necessity to people with expression number 8, but they often many seem withdrawn or distant. They fear rejection so they will likely never initiate relationship discussions. Early in life eights will be so caught up in their work that they must have a distraction to grow spiritually and emotionally. Once they realize that finding a mate is something they want, they’ll be more likely to focus on making a relationship work. The eight’s partner will offer an outlet from their career and provide the love and admiration that is fundamental to an eight. Once they have settled down, they will do whatever they must to support a mate or family.",

  "To foster healthy relationships, an eight must learn balance. They are so focused on work that they must make an effort to split their time equally between all of their efforts. An eight must learn patience and the true value of prosperity. Because they are often wealthy, they may appear shallow or possessive to others. They should not allow the pursuit of wealth to distract them from maintaining positive relationships with friends, partners and family. Eights must be careful about how they speak to others. Honesty is one of their most redeeming qualities. However, this can often come off sharp and hurt people’s feelings."

  ]

  elsif self.number == 9

  [
  "The  expression number nine in numerology is the number associated with universal love. People born with this number are resilient and optimistic. Nines are equipped to handle any curve ball life throws their way, and this enthusiasm is contagious to those around them. Nonjudgmental, sympathetic and understanding, nines are destined to be humanitarians that make a substantial impact on the world around them. They will develop both spiritually and mentally throughout life.",

  "Number 9 is associated with the best qualities a person can have: kindheartedness, loyalty, curiosity, care, understanding and empathy. The best way for you to express yourself is to open your feelings, don't be afraid to manifest your sympathy and kindness. If you feel good, helping people, try to make it your job. You are in good relationships with others, and if someone is asked to describe you in one word, this word will be nice. You are a source of inspiration for people around. Number 9 usually provides numerous talents, but mostly they need to be developed. You definitely have some tendencies, so just try to develop as more skills as you can, and you will be amazed about the things you are capable of. People like you are great social workers, doctors, attorneys and diplomats.",

  "You are very communicative person. But you always know the limit. You don't like when others are interested in your private life, because you really value the relationships with your friends and family. You are the person that inspires others; a conversation with you may open eyes to a person that was in doubt for a long time. Even such a great number as 9 has some shortcomings: if it is manifested negatively all the kindness of a person is oriented inwards, on the self, so the person is selfish. Also you need a friend as nice as you are right beside you, because in times of trouble if you don't find the support, you can get lost and make a wrong decision. In such case you will feel apathy, depression and no desire to move on.",

  "Nines are compassionate, kind, artistic, forgiving, friendly, restless, physical, intellectual, assertive, trusting and willful. People born of this number are considered introverted and are only truly satisfied serving others. They learn selflessness and compassion because they experience the gamut of difficult situations throughout life. Nines have a divine love and appreciate for friends and family. They feel at home while interpreting a beautiful painting or listening to a symphony. They are capable of intense feelings and emotions, which help them relate to others easily. Nines enjoy life’s luxuries but aren’t overly concerned with material things.",

  "Many expression number 9 people can be found in high-pressure jobs that require them to think on their feet while also sacrificing for others. They are motivated in environments that work on deadlines, and they aren’t intimidated by making progressive steps to reach a higher level in their field. Nines must have a career that is both demanding and challenging. Once they’ve found a position that fits them well, their eagerness to get the job done well and tackle huge tasks, will allow them to reach the top. Nines will excel in fields like law enforcement, finance, legal fields, medicine, and journalism. Their tenacity in work often makes them appear aggressive. This trait can make less diligent coworkers uneasy.",

  "People with  expression number nine are smitten with the idea of being in love. They’re attractive and have extreme sex appeal. Together, these qualities will lead to many admirers and mates. Their love life tends to be a bit hectic, but once they’ve decided to have one partner they’ll be devoted to that person only. A relationship with a nine must be passionate and exciting. Otherwise, they’ll likely lose interest. Romantic gestures will quickly win them over, but if they feel that their feelings are not reciprocated, they’ll move on to other romantic options. Also, because of their emotional nature, they tend to be very jealous partners. Expect a bit of drama in a relationship with a nine. A nine must realize that their ability to bounce back from disappointments is not simultaneous among people of all destiny numbers. They must learn that it can take others much longer to move on after experiencing hardships. In their drive to protect and help others, they can often adopt an uncompromising attitude. This quality can help them achieve great heights during life, but their hard-nosed approach can often be at the expensive of other’s feelings. If nines select a path that does not benefit others, they can often take on an opposite characteristic of their true nature (selfishness).",

  ]
  elsif self.number == 11
  [
  " expression number 11 is interesting because it can be reduced to a two under certain conditions. This vibration is considered a master number. Throughout life, it will become clearer as to which category people fall. Generally speaking, an 11 is a more positive  expression number than a two, and there is some contention among people on when to change an 11 to a two. Throughout life, 11s will walk a path of spiritual enlightenment, and they will inspire others. Elevens are the most intuitive of all the numbers, and will understand the unique aspects of all the relationships around them. Many will live in the limelight and raise spiritual awareness because they are so sensitive to others.",

  "People with  expression number 11 are artistic, aware, lucky, intellectual, powerful, enlightened, creative, sensitive, extreme, enthusiastic, intuitive, inspiring and radical. Elevens have an incredibly strong intuition, which best benefits the world when they can lead others to their spiritual journey. People with this sign value refinement and they are normally honest and compassionate. They are confident individuals, and their ambitions can sometimes take precedence over maintaining important relationships. People who are strong 11s may spend a lot of time pondering things instead of doing them. They can be dramatic or extreme, but they always have a unique perspective and can see the bigger picture. Elevens can also be somewhat high-strung and are attracted to physical beauty. Elevens rely heavily on faith rather than logic. They work well in large groups, and people often favor them because of their beauty and charisma. However, their strong intuitive nature can cause them to develop severe phobias.",

  "Elevens can succeed in many positions at once; specifically when they can combine hobbies, activities and work. A person with the  expression number 11 will excel in fields like ministry, teaching, photography, music, business, media, design, public relations or as a spiritualist.",

  "People with the  expression number 11 normally find partners that have similar interests and personalities. Elevens are attractive and passionate. They prefer a lover that can be gentle, and they will put all their energies and effort into understanding their mate’s needs. It is easy for a person with this number to form lasting partnerships. Even if they marry young, they’ll likely be faithful for life. An 11 also loves to be pampered with luxurious, sensual gifts.",

  "Sometimes a person who is predominately an expression number 11 will daydream, think or ponder rather than act. This can lead them down a path of laziness, which is an entirely different path than what they’re deemed to accomplish. Because of their love of luxury, they can become materialistic. An 11 must learn to accept and give praise as recognition rather than lavished gifts. Their happiness is in no way linked to their possessions. Elevens are particularly emotional and can bounce from one extreme to the other very quickly. Because of their somewhat addictive nature, the intense highs and lows can lead to substance abuse. Their goal must be to find balance or an outlet when their feelings reach a polar extreme.",

  "You have an incredible amount of power, but you probably don’t know this (though you may always have had a sense of being “different” in some way). You possess intense empathy and are naturally in tune with the universe. This can be a great tool, but you need to learn how to ground yourself as well (e.g. through meditation and time alone)."
  ]

  elsif self.number == 22
  [
  "The  expression number 22 is considered a master number. It can be kept as a double-digit number or reduced down to a single digit (four). This number is considered the master builder, and people with this  expression number will likely reach and surpass all their dreams while making a strong impact on others. Twenty-twos will assume great responsibility during life, and their huge achievements and undertakings will give them far-reaching notoriety. They will influence the world in a practical way, and often become very wealthy and successful.",

  "People with the master number 22 are born knowing what they must accomplish. They have a sense of the type of impact they can make, but the sheer amount of effort and time makes them dubious of their abilities. Because of the large responsibilities that a 22 will face, some choose to settle as a  expression number four. If this route is chosen, there will always be an emotional tug and pull. Their talents and leadership skills are far-reaching, and they will be the most successful of all destiny numbers. Twenty-twos are disciplined, hard-working, fair, driven, successful, confident, practical, intuitive, honest, independent and powerful. They are a unique combination of destiny numbers 11 and four. Elevens are known for their strong intuition and fours for their practicality. These traits work in tandem to create a person who is both level headed and focused. Twenty-twos are full of big ideas, and they are the most likely of all the destiny numbers to accomplish them. A strong sense of self-confidence will allow them to be bold leaders.",

  "They are excellent communicators that have a sensitive side. Their thick skin makes them appear less vulnerable, and they’re more resistant to criticism. Even though a 22 seems predestined to make all their ideas realities, they can lack enough perseverance for their dreams to take shape. Their potential can be wasted if they lack ambition or become overwhelmed by their path. This could result in devastating failure.",

  "Almost any position is attainable for a person with this master number. Because they approach sensitive subjects with realism and delicacy, people who are born of this number make excellent doctors, CEOs, architects, counselors and diplomats. They can make the tough calls, but are sensitive to the feelings of others. Because of their divine intellect, 22s also excel in academic fields and teaching. Expression number 22 people must choose a partner whose ambitions match their own. Once this person is found, they will be a dedicated and understanding mate and friend. They are eager to help the people they love triumph over the toughest situations.",

  "Even though 22s are more apt to achieve greatness in life that doesn’t mean they’re less likely to face hardships. The greatest strife that a 22 must endure is learning to persevere when the odds are stacked against them, which will often happen. Though they have a much tougher exterior, 22s are internally sentimental. They must not allow the criticisms of others to sabotage them on their road to greatness.",

  "You’re a dreamer with an amazing imagination and a non-judgmental attitude that makes others feel welcome. As one of the Master Numbers, you have the ability to change the world. However, that will involve stepping out of your comfort zone and taking some risks."
  ]
  elsif self.number == 33
  [
  "People with your number are often called “Master Teachers”, specifically in reference to your ability to teach others wisdom and help them become enlightened. You are a caring, sacrificing person (similar to a 6), but you also hold the potential to have enormous influence on others. Use it wisely, as you attract people to you without even trying.",

  "The  expression number 33 gives a person outstanding creative and artistic abilities. Owners of this number are able to create beautiful and unusual things. Service to people is the prevailing need for spiritual development. Those born under the influence of the master number 33 are true spiritual leaders, gifted with natural wisdom and inner strength, which contributes to the fact that they are honored with the highest honors and privileges, as well as recognition and glory in any field of human activity. However, these people live in tremendous nervous tension, which can upset their mental balance. In such situations, the negative aspects of these numbers may appear, and then these people become idle, rude and arrogant, unable to accept the reality in which they live. These personalities are endowed with higher consciousness and inner light, thanks to which they understand that the true goals in life can only be the improvement of one’s own “I” and service to one’s neighbors.",

  "People who have the expression number 33 in their numerology portrait are distinguished by outstanding intuition, as well as artistic and creative abilities. Everything that they create is hard to beat, for these people have an unusually subtle sense of beauty. These people are very attached to family life, and this attachment grows into self-sacrifice and abandonment of their own goals, if it requires the well-being of loved ones. These are dreamers and idealists, and intuition and susceptibility allow them to improve their knowledge in the field of occult sciences, mysticism and supernatural phenomena. All actions of these people are subject to moral and ethical principles. Being a kind of spiritual mentor to others, they are most demanding of themselves. They are universally respected and recognized, often honored with the highest honors and glory.",

  "The problem of this number is to learn to focus your emotionality on spiritual goals. The task is to understand that service and responsibility are joy, if they come from a loving heart. The biggest problem of the  expression number33 is to focus your emotions on higher goals in unison with spiritual laws instead of trying to solve all the problems of humanity. This control number is present on earth to learn composure, expression of love and kindness, and a willing response to the needs of others. If 33 remembers the universal principle “everything has its cause”, it will avoid stress and find balance. Thus, the  expression number33 will find the direction of its own spiritual growth. Holders of the  expression number33 may encounter the problem of misunderstanding where their help is really needed, being impressed by someone’s touching stories and not knowing how to separate the facts from the fiction. They learn that they cannot be everything to all people. Remember that the numbers 33/6 have come to learn self-government through loving service and should always strive for balance, emotional and spiritual. A clear expression of one’s own needs and a willingness to allow others to be responsible for themselves is part of what should be learned in this life. A sacrifice is valuable as long as there is a “self” offering up. The  expression number33 can be the #{"Cosmic Parent"} and the Master of healing energy, but, like all parents and healers, the number 33 should leave something for themselves."
  ]
      end
    end
  end
