class Personality < ApplicationRecord
  has_many :charts
  has_many :users, through: :charts

  def short_description

   if self.number == 1
"Personality Number 1’s are creative thinkers and outgoing, which means they can come up with unique solutions to problems. People will look to them to do this. 1 vibrates as forward, positive progress. On the negative side, Personality Number 1’s can doubt themselves and become gloomy. They need to remember the world sees them as capable leaders who make good decisions."
  elsif self.number == 2
"Numerology number 2 personalities seek balance and peace in all things. Equilibrium is very important to the number 2. They do well in resolving problems for others, but must learn to make decisions for themselves. They must learn to keep a level head when faced with imbalance and to stick with their decisions. Number 2s are creative and are a great advantage in friendships and relationships of all kinds. Many number are at play in the complex make up of any one person. Those guided primarily by the number 2 are said to have number 2 personalities and will find themselves in this category in most of their interactions."
  elsif self.number == 3
"Those ruled by personality number 3 are very intelligent and pragmatic. They can achieve great success. They must take care to develop their concentration and ability to follow through with projects to achieve that success. They tend to be lucky, but they must work with that luck to create the success for which they yearn. Number 3s are popular and can do very well for themselves with some determination."
  elsif self.number == 4
"Numerology personality number 4s are traditional people who prefer to be noticed for their work over any other attribute. They can be difficult to get along with for those who disagree with their values and ways of doing things. They make great employees in many situations. If they can learn to embrace change and become a bit more flexible, 4s can become even more successful."
  elsif self.number == 5
"Number 5s are fun-loving lives of the party. This can draw in a constant flow of new friends and relationships. What a number 5 has in charisma, it often lacks in commitment. Numerology personality number 5s tend to look to satisfy their immediate urges and would do well to gain discipline by any means possible."
  elsif self.number == 6
"Numerology personality number 6 is the most caring and nurturing of all numbers. They will tend to others at the expense of themselves. They value harmony above all else. They must learn to care for themselves in their interactions with others. Their caring and understanding nature will attract those in need of comfort and they will feel most fulfilled in providing that comfort."
  elsif self.number == 7
"Numerology personality number 7s tend to enjoy the company only of themselves. The capacity of their mind and their natural instinct to question everything around them allows them to be quite happy alone.   They look deeper and expect everything to be more than it seems on the surface. Their interactions with others an be stilted at best. Number 7s should pay attention to their relations with others in order to get along well. They will be successful in any number of exacting careers in academics, science, and mathematics."
  elsif self.number == 8
"Personality Number 8 is an interesting balance of work and play. You can be the life of the party and still lonely at times. "
  elsif self.number == 9
"Numerology personality number 9 is one of the most controversial of all personality types. Many people will love and admire you while others despise you. Many actors and musicians are personality number nine"
  elsif self.number == 11
"You are numerology personality number 11. You have been fighting internal battles most of your life yet you remain kind and humble."
  elsif self.number == 22
"The master number 22 is the most powerful value in numerology. People who possess this number will experience vast success and support during their lifetime. This number, which is known has the Master Builder, has retained the some of the most desirable characteristics from master number 11 and number four and amplified them. They have a practical nature, and can be overwhelmed or challenged by their gifts and potential. They must learn to ward off negative thoughts with positive ideas. If they can learn to hone these abilities any ambitious vision, no matter how large, can be attained. Their potential is virtually limitless."
  elsif self.number == 33
"The master number 33 is an incredibly rare vibration and combines both master numbers 11 and 22. Though there is some contention among experts, life number 33 is considered the perfect balance between the master numbers. During their lifetime, people with this path number, will become a brilliant religious or spiritual trailblazer. These individuals are often born caregivers, and their nurturing nature allows them to devote themselves wholly to any worldly cause. Known as the master teacher, they are driven by the most unselfish goals and are responsible, supportive and kind. They have no personal schemes and are not driven by ulterior motives. Their tender nature makes them a powerful advocate for any altruistic campaign. Their goal in life is to serve as many people as possible."
  end

  end

  def long_description
    if self.number == 1
  [
"Others see people with Personality Number 1 as decisive and efficient. Number 1’s come across as capable and energetic. People with Personality Number 1 command respect, but they have to be careful of intimidating others without meaning to. They are competitive, driven and motivated, and come across as loyal individualists. They don’t mind taking risks or being the first to dive right in. People who have Personality Number 1 have a clear sense of self. They hold strong values that they are not afraid to defend . 1’s also are the first to volunteer for new responsibilities and duties at work. At home, they are seen as the responsible leader. You are a natural leader, full of drive and determination. You are however unnerved by responsibility. You are at your most productive when left alone. You are concerned about your appearance. You participate in sporting activities, often to regain your inner balance.",

"You are a romantic idealist though a bit immature. However, you are farsighted and have the ability to influence others. You have the ability to transform microscopic bits into a macroscopic whole. However, your single-mindedness sometimes causes you to be insensitive to others. You are confused about your values and thus don't see the whole picture very often. Your desire to help others sometimes comes in the way of your personal growth. You will have to arrive at a happy balance between your ideals and your personal growth. You focus on the big picture. Your penchant for moving goalposts can have serious consequences. You recognise the equilibrium between the rational and the irrational and can easily combine the two in your thought process. You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focussed to succeed.",

"You are very motivating and amiable. Opportunities come your way constantly but you don't optimise on these. Don't expect your charm to steer you out of every tight spot. You are very emotional and should stay away from seeking cheap popularity. You should have an even approach towards issues you feel strongly about. You must control your anger and learn to be more compassionate and understanding. You must look at the larger picture and respect the other person's point of view.n You thrive on change and like exploring new ideas, meeting new people, discovering exotic places. You are witty and resourceful. You like the company of like-minded people.",

"People who have a strong connection with this number have a very difficult life and usually encounter difficult situations, but these people are not surrender and do not give up easily, but continue their fight.",

"They are great fighters and can survive in difficult conditions, you will never see them sad and behind every negative and bad situation they will find something nice and successful to get something smart and wise behind every event. However, these people are often separated from their family and friends, and this build a cold relationship between them. These people love autonomy, they do not like to receive help and seek help from other people."
]

    elsif self.number == 2

[
"Number 2s bring a sense of balance to everything. They are able to see all sides of an issue. They look for a harmonious outcome in all situations. Bickering or quarreling is very unsettling. They make great mediators. They are very understanding. Number 2s are good diplomats. They are intuitive and understanding in nature. When people seek honest advice, they often seek out a number 2 personality. They tend to be very philosophical in nature. Number 2s are well-liked by all. People are naturally drawn to a number 2. They are an asset in all relationships. They are very tactful in their dealings with others. They are caring and loving of others, often to the detriment of themselves. Number 2s thrive where there is creativity and a sense of balance. They do well in creative careers. Music, painting, art of many kinds and writing fiction, poetry, or plays are all worthwhile endeavors for a number 2 personality.",

"You are a dreamer and thus tend to be a bit naïve. You are a visionary with a messianic streak. You are creative and can organise bits of knowledge into a unified whole. Your obsession with your cause makes you neglect those close to you. You are a live wire and extremely talented, but are too hard on yourself. You set yourself impossible targets and get frustrated and depressed when you can't achieve those goals. Though you are a team player with lots of patience, you are sometimes overtaken by a sense of alienation. You are a very sceptical person and don't trust people easily. Thus you don't have a role model whose ideals you can emulate. You will have to find some philosophy and some companionship to widen your horizons. Otherwise you risk loneliness and isolation.",

"You are very motivating and amiable. Good luck has brought you many opportunities but you do not optimise on these. Don't expect your charm to steer you out of every tight spot. You are very emotional and should stay away from seeking cheap popularity. You should have an even approach towards issues you feel strongly about. You must control your anger and learn to be more compassionate and understanding. You must look at the larger picture and respect the other person's point of view. You thrive on change and like exploring new ideas, meeting new people, discovering exotic places. You are witty and resourceful. You like the company of like-minded people.",

"Number 2 can bring you many positive features and can help you to see future challenges more clearly and to deal with them in the right way. This number represents sincerity and positive energy and can bring you many positive thoughts. Number 2 plays an important role in numerology, and if this is your number then you can expect nice periods in the near future. Number 2 is also a symbol of peace and tranquility and this number describes people with a positive and peaceful character. This number helps people to think better and direct their energy to work and important things in life. Number 2 also presents people with work habits and who are ready to work and advance in order to improve their business career. Number 2 can also symbolize knowledge and progress, and if this is your number you can expect new challenges in your career.",

"Number 2 at the date of birth is sincere, good and highly knowledgeable, and this number can describe your vibrant path that will be positive. Number 2 plays an important role in love, and he can make progress in romantic relationships and in marriage. For this number we can also say that he describes many celebrities and many athletes, actors, politicians, etc. It is thought that their number 2 has brought them a lot of luck and that with the help of this number they managed to make progress. Number 2 in numerology also represents knowledge, happiness, and experience."
]

    elsif self.number == 3
[
"Number 3s are simply fun to be around. They have a quick wit. They are usually the life of the party. They have excellent social skills. Number 3s tend to be very charming. They are wise and crave knowledge in all areas. They are intellectual and very pragmatic. They are very ambitious and confident in their careers. Their strong suit includes carrying out of instructions and plans because they are very disciplined. Number 3s are confident. They create great possibilities for themselves and others. They mature quickly. They can secure financial freedom with a good deal of effort.",

"Personality number 3s are driven to succeed at the highest levels and to achieve the top position in their careers. Careers in which a personality number 3 will excel and find happiness can include politics and public offices. Banking and advertising may be suitable careers. Many personality number 3s do well in the armed forces as there are ranks within which they may move up. Medicine may also be a good field for number 3s.",

"Like King Midas, everything you touch turns to gold. Yet you are isolated from other aspects of life. You need to find answers to various questions in order to fill the spiritual vacuum in your life. Only then will you achieve a balance between your spiritual and material needs. Scientific and philosophical questions intrigue you. You have an introspective and investigative bent of mind and the single-mindedness required for research. You are obsessed with perfection but don't let the driving need to succeed rule your life. Your calm and detached manner causes you to be rather introverted. Use discretion and tact to solve problems and your efforts will be rewarded. Swim with the tide; don't let depression get the better of you. You are very emotional; try to be more objective.",

"You are a good listener. You pay a lot of attention to detail, but this often results in your losing sight of the larger picture. You have a highly developed sense of justice and fair play, a trait shared by many people in the legal field. You are a live wire, always in control of a situation. You like charting your own course and are not averse to taking risks. You are also original and resourceful. You like people who are not unnerved by adversity. You are concerned with your appearance and follow your own style. Your tough exterior often intimidates others.",

"You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focused to succeed. You are reliable. You are witty and creative. You have a positive frame of mind and are very inspiring and bighearted. When your feelings are hurt you withdraw into a shell but your cheerful nature pulls you through. Be careful, lest you lapse into depression and cynicism. You thrive on change and like exploring new ideas, meeting new people, discovering exotic places. You are witty and resourceful. You like the company of like-minded people. You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focused to succeed.",

"We can say that these people are dedicated to work and obligations and they are enjoying helping people and interacting with them. In addition to these features, we must note that these people are very funny and they love taking other people’s attention, for that reason they like to be in the center of attention."
]

    elsif self.number == 4
[
"Numerology personality number 4s are perfect employees. Their attention to detail and order enables them to complete projects perfectly and in a timely manner. They will often complete work under budget. They are trustworthy. Others see number 4s as reliable. They are very consistent and do not like to draw attention to themselves. They tend to wear earth tones and understated clothing. They prefer to be judged based on their work rather than their appearance. They tend to be less social than other numbers. Personality number 4s hold traditional values. They thrive on order and will create systems where none exist. They need organization in their work and personal lives. They are seen as solid leaders. 4s believe that success can come only through hard work and diligence. Their true goal is to bring order to the lives of everyone around them and to bring plans into fruition. The number 4 is the number of fate, though, so many things can happen in the life of a personality number 4 over which the 4 has no control.",

"Personality number 4s want to be recognized for their work. They flourish in an environment where they are rewarded. This makes them tend to be happier at smaller firms where they get the recognition they so desire. They fair better in positions with a repetitive schedule and where their attention to detail can be put to the test. Careers in accounting, banking, and financial services are perfect fits for number 4s. They can also do well as scientists and engineers or building contractors. These fields allow them to shine and be rewarded.",

"Though aware of the problems around you, you do little about them. Your contentment will be closely linked with your ability to look beyond yourself and you will have ample opportunities to work selflessly. You will also need to overcome your intolerance, as you will be involved with people from varied backgrounds. You are an excellent communicator and very artistic. Though you are a team player, you try to retain a degree of independence. You are quick on the uptake but need to discipline your thought process. You are also a risk taker. You are very emotional and have to try hard to develop lasting relationships. You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focussed to succeed.",

"You are thoughtful and kind. You are admired for your fair play and kindness. You are creative and like beautiful things. You are protective of those you love; people relax easily in your presence. You can summarise a whole lot of different ideas and reach a consensus. You are systematic in your approach. You have a unique insight and thrash things out very thoroughly before arriving at a decision. You dislike impulsiveness and your analytical skills help you get to the heart of the matter. You have little time for fantasy and prefer hard facts. You are detached and distant in your relationships. You should have an even approach towards issues you feel strongly about. You must control your anger and learn to be more compassionate and understanding. You should look at the larger picture and respect the other person's point of view.",

"You undertake tasks after thorough preparation and are usually in control of a situation. Your determination will take you a long way. You are a realist. You also possess high ideals like honesty and fair play, and want to make the world a better place. You need to be more flexible in your ideas. Others sometimes depend on the ability of people in number 4 who have to face with life challenges and are attracted to the stability they possess. They are trusted friends and do not change their minds easily."
]
  elsif self.number == 5

[
"Numerology personality number 5s enjoy freedom. They are quintessential adventurers. Their life is an ongoing adventure. They are very adaptable and are able to gain the most out of every opportunity that presents itself to them. Others see in number 5s a very strong potential for success. Others tend to follow a number 5 personality for that reason. Personality number 5s are great self-promoters. Their self-promotion brings success to their lives in which others would miss out. In social situations, personality number 5s tend to brighten every social gathering. They dress fashionably and will often look great in bright colors. They are upbeat and optimistic. Their charisma makes them popular and draws others to them. People learn to anticipate the unforeseen from number 5s. They are curious people who thrive on change. They like to stay moving.",

"Work life is secondary to number 5s. They see it as a means that allows them to enjoy their lifestyle. They feel little sense of duty to their employers. They will tend to change jobs as frequently as relationships. They do not do well in dull or boring jobs. Number 5s will fair much better in jobs relating to a personal interest or hobby. Self-employment if often favorable to a more traditional employment situation. Sales and advertising careers are sometimes able to hold the interest of number 5s for a substantial time. They need constant change and a career that affords them something different every day. Travel and the outdoors are job qualities that will appeal to personality number 5s.",

"The mysterious of nature will fascinate you and you will be drawn towards surreal things in life. For you, love is important and is not driven by logic. You have natural charm in abundance but are not afraid to point out flaws and mistakes when you notice them. If you need to make a point, you go right ahead. You come across as pleasant and soothing to others. Your daydreams are vivid and you often indulge in fantasies.
When faced with a difficult situation you tend behave like an ostrich - you bury your head in the sand! Get your power of reasoning to help you tackle such problems. Don't let your emotion cloud your judgement. A dispassionate approach will help you find the answers.",

"You are an excellent communicator and very artistic. Though you are a team player, you wish to retain a certain degree of independence. You are quick on the uptake but need to discipline your thought process. You are also a risk taker. You are very emotional and have to try hard to develop lasting relationships. You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focused to succeed. You are very motivating and amiable. Innumerable opportunities have come your way but you have not optimised on these for one reason or the other. You are a good talker, but don't expect your charm to steer you out of every tight spot. You are very emotional and should stay away from seeking cheap popularity.",

"You have an independent streak. You like to enjoy life to the fullest. You are impulsive and often regret your actions. You have to stand up for yourself and develop a strong sense of self-esteem. Don't be swayed by others - develop your own individual style and value system. You will mature into a person with original ideas. You have great potential for success. You have an eye for detail yet you don't lose sight of the larger picture. You work hard to turn your dreams to reality. You should put your natural intuitiveness to good use. You strive for freedom and success. You are smart and witty. You have an individualistic streak and distinct style. You feel restricted by routine and feel the need to lead the way. Take care, however that you don't lose your sense of balance.",

"You have an independent streak. You like to enjoy life to the fullest. You are impulsive and often regret your actions. You have to stand up for yourself and develop a strong sense of self-esteem. Don't be swayed by others - develop your own individual style and value system. You will mature into a person with original ideas. You have great potential for success. You have an eye for detail yet you don't lose sight of the larger picture. You work hard to turn your dreams to reality. You should put your natural intuitiveness to good use. You strive for freedom and success. You are smart and witty. You have an individualistic streak and distinct style. You feel restricted by routine and feel the need to lead the way. Take care, however that you don't lose your sense of balance.",
]

  elsif self.number == 6

[
"Numerology personality number 6s are loving and caring people. They are born caregivers. They are concerned with humanity and peaceful outcomes at all costs. They are known for their giving nature and warmth.  They tend to be happiest in surroundings with which they are familiar. They enjoy home and harmony. They can be artistic in nature. Number 6s are happy when teaching others and helping. They tend to attract those in need of some comfort. They are selfless and will go to great lengths to ensure the peace and happiness of others. They tend to be level-headed and take their responsibilities very seriously. When working toward a goal, number 6s can be very patient. When they are fixing things for others, curing an ailment or righting a perceived wrong, they are happiest.",

"The number 6 is sensitive and does not do well in high pressure work atmospheres. Careers in teaching or the arts may be suitable for those with the number 6. Work involving caring for others, such as some healthcare careers, are most appropriate for these people. They tend to stay loyal to their career and their position for many years. Fulfillment comes, not from the job itself, but from working with and for people.",

"Though aware of the problems surrounding you, you rarely do anything to resolve these. Your contentment will be closely linked with your ability to look beyond yourself and you will come across ample opportunities to work selflessly. You will also need to overcome your intolerance, as you will be involved with people from varied backgrounds. You are a kindhearted soul. You are the unifying factor in your family. Though humble, you take pride in your work and achievements. You have a heart of gold and want to reach out to people; but remember, you cannot help all the people, all the time.",

"You are deeply attached to nature, but at the same time you want your surroundings to be comfortable. You run away from ugly situations and are prone to get stressed out at the slightest of provocation. You are loved and admired by most people and you don’t believe in confrontations. This is the number of love and romance, so you will search the deepest corners of the world to find your Soulmate and will settle for nothing less. Inner beauty is important to you and this is visible to all. Malice is not something one will associate with you. But when threatened or you feel like a loved one is drifting away from you, feelings of jealousy cannot be ruled out. You are farsighted and focus on the larger picture. Your penchant for moving goalposts can have serious consequences. You recognise the equilibrium between the rational and the irrational and can easily combine the two in your thought process.",

"You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focused to succeed. You should have an even approach towards issues you feel strongly about. You must control your anger and learn to be more compassionate and understanding. You must look at the larger picture and respect the other person's point of view. You thrive on change and like exploring new ideas, meeting new people, discovering exotic places. You are witty and resourceful and enjoy the company of like-minded people. You value honesty and justice. You are creative with a special talent for drawing. You are reliable and give wise counsel to others. But take care not to offer unsolicited advice. You have a noble demeanour. Your calm facade belies your sensitive and vulnerable nature.",

"Their mission is to love, deny, and protect. It is necessary to align your environment. It is important for them to feel emotionally, spiritually and physically. They are very stable in everything they do. They feel the best when they help others.",

"All their activities are directed to love and to be loved. Fear and confusion are not compatible with their energies. They love their world in peace and comfort. They are mentally strong and it is good that power is used for positive purposes. When they believe in something, they are strongly involved in it. You can rely on them, and expect a fair relationship in return.They can sometimes act as too protective and dominant in their intent to help. They need stimulation to feel alive because the opposite can bring depression. They like their rhythm of life and do not like when others are hurrying them. They are great partners because they crave for harmony.",

"They can sometimes be stubborn, but you can rely on them. As far as their behavior in relationships is concerned, they tend to compromise to avoid quarrels. They are very supporting for partners in their relationships; they like to please their partners and are generally stable and balanced. They will find way to provide all the material needs for themselves and partners, and often find ways of linking love, wealth, and relaxation to the home and family environment."
]

  elsif self.number == 7

[
"Numerology personality number 7 tends to look deeper. They look for the hidden meaning rather than taking each thing as it immediately seems.   Their intellectual nature may not always be obvious. They have a strong mind and know that things usually are not what they seem. They have excellent taste. Number 7s have a passion for art that includes a deep understanding. They are very independent and pride themselves on their self-sufficiency. They prefer to rely on themselves and their own mind. Lifelong knowledge seeking is important to the personality number 7. They can be known as eccentric loaners. Number 7s can be inventors and deep thinkers. They are philosophical and possess a deep inner strength.   They are not ones to gossip and remove themselves completely from petty disagreements and backstabbing.",

"The great mental capacity of the numerology personality number 7 often compels number 7s into mathematics and science. Academics can also be a fulfilling career for the number 7. Physics and chemistry are good career choices, as are any of the exacting sciences. Number 7s can excel in business dealings as well. Any career requiring logic and the methodical thinking is strongly suited for personality number 7s and they will find a great deal of success in these positions.",

"You are an intellectual, capable of great insight. You are an introvert but you must take care not to get isolated from others. You have to try and maintain your independence without getting cut off from society. You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focused to succeed. You are not easily swayed by others and are an imaginative thinker. You tend to follow a single line of thought at a time. You generally prevail in academic discussions.",

"You feel that you stand out from the crowd but can't figure out what sets you apart. Childhood shyness makes you very vulnerable. You choose friends with great care and rarely share secrets. You hesitate to show your sensual side. You are also a naïve romantic dreamer. This makes you somewhat disorganised. You are also very emotional and expect a lot from your relationships. You have a noble demeanour. You are keen to help others and improve their lot. Your calm façade belies your sensitive and vulnerable nature. You should have an even approach towards issues you feel strongly about. You must control your anger and learn to be more compassionate and understanding. Look at the larger picture and respect the other person's point of view.",

"You sometimes suffer from low self-esteem. As a result you severely criticise yourself and curb your potential. This further results in your isolation. You must find some creative outlet for your fertile imagination. Learn to value yourself. You strive for freedom and success. You are smart and witty. You have an individualistic streak and distinct style. You feel restricted by routine and feel the need to lead the way. Take care however, that you don't lose your sense of balance.",

"Most of their brilliant, original ideas come from dreams or from day-to-day fantasies that are their favorite blunders. They try to get acquainted with dream secrets and subconscious mind, and they believe in mystical power that people can take from the future or the past. They are surrounded by members of the opposite sex who are attracted to them, and flirt with them in a special way.Number 7 indicates mysticism, intuition, mystery.They are blessed with wisdom, spiritual qualities, and visionary abilities. Neptune also makesthese people intuitive and able to bind to higher degrees of existence.These people are prone to mysticism and occultism, they are always in search of knowledge. They are ready to devote their lives to the ideal they believe in, without worrying about their material success. These people possess a brilliant mind that is capable of unifying material and spiritual aspectsas a whole. They actually carry a lively world within themselves. They love traveling and life time often takes them overseas, and life itself is full of unusual circumstances. They have a positive and soothing effect on their environment.If they develop healing or other supernatural abilities, they achieve great success.",

"They are very noble; their greatest ideal is sincere and true love. Best match with people born under number 2. Their biggest drawbacks are that they do not have the strength in themselves.Number seven offers to these people a lot of talents; they make sense to music, painting, dance, and even spiritual disciplines. They are very often unaware of these talents and need the other people to direct them. They tend to dream and run away from reality.They have a special magnetism in them that others like. They are in love with romantic people who seek spirituality and are closely related to them. They seek partners who will understand and accept what they are."
]

  elsif self.number == 8
[
"You are confident and outgoing. You have strong opinions and you’re not afraid to say what you mean. You have the ability to take command of a situation and influence others. You are a born leader and you quickly advance in all areas of life. When you want something you go for it. People gravitate towards your positive energy and admire your motivation. You appreciate quality in all things life has to offer. You don’t mind splurging on the best that money can buy. You work hard so you deserve to enjoy the fruits of your labor. You are usually the best dressed in the room and when you make an appearance somewhere your presence is felt. Heads turn and people notice you. There’s nothing low key about your personality.",

"You’re not afraid to look people right in the eye and tell them what you want. Your strength and power intimidates many people around you. You are admired by many but people fear being on your bad side. People often turn to you for guidance and you know just how to handle it. Whether it be at home with family, dealing with friends or issues at the work place. You’re not afraid to help people when they truly need it. You also have no tolerance for nonsense. You are loyal, dependable and hard working. You expect the same from those around you and you have no patience for lazy people. You are truly generous and caring to the people around you. This often means working long hours and putting your loved ones problem’s before your own. You are not content unless your loved ones are happy.",

"You are a bit disorderly and have a distorted sense of priorities. You find it difficult to see a project through to its logical conclusion as you lose sight of your objectives. You will need firm resolve and dedication to succeed. You are a capable administrator and have excellent business acumen. You are farsighted, but a little reckless. Don't brood over failure - get on with your life. Try to develop your will power but don't let ruthlessness take over. You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focused to succeed. You are not easily swayed by others and are an imaginative thinker. You tend to follow a single line of thought at a time. You generally prevail in academic discussions.",

"You feel that you stand out from the crowd but can't figure out what sets you apart. Childhood shyness makes you very vulnerable. You choose friends with great care and rarely share secrets. You hesitate to show your sensual side. You are also a naïve romantic dreamer. You are also very emotional and expect a lot from your relationships. You have a noble demeanour. You are a humanitarian who is keen to help others improve their lot. Your calm façade belies your sensitive and vulnerable nature. You should have an even approach towards issues you feel strongly about. You must control your anger and be more compassionate and understanding. Look at the larger picture and respect the other person's point of view. You strive for freedom and success. You are smart and witty. You have an individualistic streak and distinct style. You feel restricted by routine. You need to lead the way. Take care, however that you don't lose your sense of balance."
]
  elsif self.number == 9
[
"You are extremely confident and outgoing. Your confidence is evident in every aspect of your being from your clothing style to the way you speak. Many people find you arrogant and at times they are right. Some are jealous of how confident and outgoing you are. These people will try to belittle you and talk behind your back. You couldn’t care less. You aren’t afraid to speak your mind regardless of who’s listening. This will make many people dislike you although causing controversy is never your intention. Those that do agree with you will be drawn to you immediately. You have many friends and admirers. People love and respect you. You are often the center of attention and the life of the party. People either love you or hate you right away. You are rarely the quiet person hiding in the corner. You enjoy art, fashion and music. Your home and wardrobe is a direct reflection of your personality. You aren’t afraid to take risks and express yourself. You are extremely comfortable in your own skin and the world knows it.",

"Many people are interested to your to hear your opinions. You are always happy to give people guidance when asked. You can come off as hard and insensitive but deep down you are a loving person who truly cares about humanity. You are interested in helping those in need. You realize that you have more then you need to live comfortably and you feel obligated to give back. You take great joy in making other people’s lives better.",

"Learn to square up to your responsibilities. Stop trying to find solace in drink. You are capable of finding novel answers to your problems if you apply yourself. You are a live wire always in control of a situation. You like charting your own course and are not averse to taking risks. You are also original and resourceful. You like people who are not unnerved by adversity. You are quite taken up with your appearance and like to follow your own style. Your tough exterior often intimidates others. You are flexible and love challenges but tend to be impulsive. You are ingenious and witty. You have a multifaceted personality but you need to be more focussed to succeed.",

"You are tactful and diplomatic. You are a very intuitive thinker and amenable to new ideas but take care not to be too swayed by others. You have a keen civic sense and want to help the less fortunate. While you focus on the macroscopic whole you forget the microscopic components. You look at life through rose tinted glasses and the reality saddens you. Your enthusiasm helps you to meet your commitments. You are not very expressive about your feelings. You have a positive attitude and can communicate your feelings. You need to discipline your passions and sort out your priorities. Your strength lies in the creative field, so it is time to give your life a goal. You are very emotional and take offence where none was intended. Guard against becoming cynical and sarcastic.",

"You strive for freedom and success. You are smart and witty and have an individualistic streak. You feel restricted by routine and feel the need to lead the way. Take care, however that you don't lose your sense of balance. Your zeal for life clouds your judgement. You have the tendency to give in to your indulgences. You must learn to be tolerant and compassionate. Stand by your commitments. Don't run away when the going gets tough."
]
  elsif self.number == 11
[
"You were very shy as a child and many of those feelings still remain to this day. You battle with anxiety and avoid any situations where you will feel stressed. You are quiet and try to stay low key. This quiet nature is reflected in your clothing style as well as your speech. You rarely take risks or speak your mind to strangers. It’s difficult for you to really open up to strangers therefor your circle of friends is small and tight knit. You are extremely kind, caring and warm hearted. Your loved ones know they can depend on you being there for them in a time of need. The opposite sex is attracted to your kind heart and fierce loyalty. You would make the ideal life partner for someone. Your gentle personality makes you an easy person to talk to. Many of your friends come to you when they are going through difficult times in their lives. People feel they confide in you and you’re always willing to help.",

"Although you can be shy and introverted at times, you genuinely enjoy helping people. You will do very well in any position where you take on the role of teacher. You enjoy being alone. This is when you can truly relax. You spend a lot of time in deep thought. Conflicts cause you major stress and anxiety and you avoid them at all costs. Fighting with loved ones leaves you feeling drained both physically and emotionally. The negative effects of a conflict can leave you feeling depressed for days.",

"You have worked hard to gain confidence and overcome, at least to some extend, an in-born shyness. As a child, and into your early twenties, nervous energy may have caused you to bite your nails or express your nervousness in other ways. You are vulnerable and you need to be more careful than most people when you choose friends. You seem an easy prey to predatory individuals. You will probably find yourself the victim of a con man or con woman more than once in your life.",

"In the eyes of most people, you are perceived as gentle; a safe harbor. People are drawn to you because, among other reasons, you radiate warmth and you are unthreatening. Your dress is neat and clean. Your clothing should be comfortable, soft, and flowing. You should avoid plain and understated clothes. Make an effort to be a little more daring and exciting in your appearance. This will balance nicely with your perceptive and open personality. The opposite sex is attracted to your gentle and attentive nature, yet senses the passion beneath your surface. You have sex appeal. Exercise is important to your appearance and to promote a level of strength you radiate.",

"You make others feel important and loved. You are sensitive and become tense in a disharmonious atmosphere. You have experienced quite a bit of negative criticism as a child, which made you shy growing up. Though you may be well past that shyness, a bit of the vulnerability has remained with you and is often sensed by others. You are a peacemaker. Arguments leave you drained. People sense your desire for harmony. But you must avoid being the blank tablet for others' projections. People may underestimate your strength, but this is a mistake. You are strong. You bend, but don't break. You have a fine sense of beauty and excellent taste. There is a grace in your movements, reflecting your keen sense of harmony and refinement."
]

  elsif self.number == 22
[
"People who possess the master number 22 are insightful, talented, courageous, intelligent, powerful, family-oriented, emotional, charismatic, practical, loving and imaginative. Because they are extremely dedicated to their goals, they have the ability to think up elaborate plans and bring them to life. They apply practical knowledge to their aspirations. If something doesn’t take shape has planned, they’ll often stick with it, even if the outcome seems bleak. Thus, they are able to create extensive empires. Being the Master Builder, they often love working with their hands, and they dislike any confrontation. Their dedication to their work can often make them appear insensitive or detached, but nothing can be further from the truth. They complete tasks with noble intentions – often for the betterment of everyone. People who are predominantly master number 22 can be unconventional, bizarre or eccentric. One of their many challenges is to develop a balance between their mental, physical and spiritual standpoints. They also require a system or routine, and have immense organizational skills.",

"People who have the master number 22 are often scientific and compassionate. This is an excellent combination for people who decide to pursue a career in the healthcare industry. Individuals who have the master number 22 will make superb doctors, nurses or counselors. Their innate ability to craft things will allow them to excel as designers or architects, as well.",

"They will offer emotional support and perspective in every relationship, and they will remain a steady and loyal partner. Though, a person with this master number might be a romantic, they often show it in objective ways because of how focused they are on their personal ambitions. By learning to understand their flaws, they will become a more well-rounded mate. A person who has this vibration should seek a spouse who can contribute to their dreams.",

"A person with a 22 master number might be overwhelmed with their gifts, and develop a negative outlook. This is extremely detrimental because their thoughts have immeasurable power and often become a reality. They must retain a powerful, optimistic outlook at all times. If they become obsessive or too focused on tangible wealth, they’ll stray from their path. Their ability to create and teach others about things that truly matter relies on their ability to steer clear from material desires. They should always strive to build something for the greater good. Those who get distracted by money-oriented undertakings can become overbearing and domineering.",

"You radiate reliability and consistency. People trust you and feel secure with your judgment. You are seen as a cornerstone of a business and are relied upon to do your work efficiently and expertly.",

"Whether it is a political movement, a business, or a philosophy, you have a strong inner drive to manifest something of major importance. Whether you know it or not, you possess great power within your being. You were born with this power in a latent state, but on some level you were aware of it. Early in life, this power manifested itself as an awkwardness and a discomfort inside of you. Your self image has always been one of contradictory extremes: on one hand you sensed your uniqueness and potential; on the other you may have felt insecure and perhaps even inferior.",

"This paradox has caused waves of self-doubt and lack of confidence. But it also is a powerful generator of energy that, when combined with the higher characteristics of the 22, can become a dynamic and unrelenting force. In order to channel such great power, you need a noble goal for which to aim. You will probably try your hand at several different kinds of work before you rise to the challenge of your true ambitions. Your ideas are so creative and superior that they inspire enthusiasm and sometimes even devotion among your co-workers. You should be involved in large enterprises or governmental institutions. You have the organizational diplomatic skills sufficient to keep difficult and delicate projects on track. Once you come into possession of your full power, there are many psychological and spiritual pitfalls to be faced. You can become arrogant and superior. You can become deluded into thinking that your judgment is beyond question, and that the advice and support of others is unnecessary. You may seek to control all power in a given enterprise.",

"This dangerous and egocentric attitude is sometimes even extended to family members who you may seek to keep under your thumb. You perform best when your domestic foundation is stable and supportive; it is very important to have a partner who shares your dreams and has high degree of strength and independence to keep up with your drive. Challenges somehow draw the best out of you.",

"You perform best when your domestic foundation is stable and supportive; it is very important to have a partner who shares your dreams and has high degree of strength and independence to keep up with your drive. Challenges somehow draw the best out of you. You tend to wear earth colors and conventional attire. You could benefit by putting a little flair in your dress. Wear more uplifting colors. Loosen your dress with less severe lines. If you wear a brown suit, include a bright tie or some jewelry.",

"You love the intimacy, consistency, and the security a family provides. You are a good provider and protector. But family members may take your efforts for granted. You are a true patriot. You love your country and are an integral part of your community. Your consistency and adherence to your well-laid plans usually pays off in a comfortable and secure future. Your human qualities - creativity, humility, understanding, and compassion - increase with the level of your performance. Therefore, commitment to excellence is central to your success and inner development."
]
  elsif self.number == 33
[
"People with this life number are happy, kind, intelligent, loving, wise, trustworthy, gentle, compassionate, spirited, intelligent, goal-driven and peaceful. They feel it is incredibly important to understand an issue in its entirety before striving to fix it. Though, a kind spirit drives them, they are also analytical and make certain that their emotions are based on facts. They seek a harmonic balance with the world, and are energetic and joyful to be around. They must make peace with the idea of standing out and being a person to which others lean on for support and advice. Regardless of their choice of career, others will follow them. They are strong leaders because of their selfless nature. They are driven solely by the concept of doing what is right. If met with doubt, a person with this master number must learn to trust their instincts.",

"Based on their enlightened and spiritual existence, one might expect to see people with master number 33 as religious or spiritual leaders, therapists, teachers or counselors. Many will look after the elderly, people with special needs or young children. Their nurturing spirit allows them to be incredibly empathetic in virtually any situation. This vibration is the most loving of all. A partner can expect to feel unconditional love and support from a person with this life number. Their devotion to love makes them excellent spouses and parents.",

"A person with master number 33 will have to overcome their personal emotions to focus more on a higher purpose and commitment. Their emotions can be extreme and unpredictable at times, and they must learn to balance their inner spirit. They should confront the troubles that lay within themselves first. Finding a foothold and their own spiritual connection is the foundation at which the bigger picture begins to unfold. Learning to find peace when being pummeled by others issues can be a heavy burden to bear, and it can cause them to experience extreme stress throughout life. Though, they analyze before they act, people with this life number have an immense desire to take on every issue at once. Maintaining composure is a challenge that must be tackled in order to triumph in their earthly purpose.",

"You inspire confidence. You have a fine sense of justice. You do everything in your power to keep the harmony and are even willing to sacrifice your personal desires for the good of others. You can take this too far, however, sometimes playing the role of the martyr.",

"You have to guard against being taken advantage of. You are not always a very good judge of character. You tend to see the best in others. You can become too involved in the lives of others, to your own detriment. (This aspect can be balanced by other numbers in your chart.) People see you as a maternal or paternal figure. They want to relax in your presence and unburden themselves. You are the safe port in the crowd. You are hospitable and domestic. You love children and are a good parent. You are romantic, faithful and very protective. The 33 is also considered a Master number, although at its core it is a 6 (3+3=6). This gives you the potential to become a major influence on your community, most likely in politics or through a non-profit organization. This will be especially true after early middle age, at which time you gain an uncommon intuitive intelligence.",

"Some of the world's greatest authors, poets, and comedians have a 33 Personality. You are artistic. You love music, flowers and gardening. You are a natural interior designer. You have an excellent sense of color and taste. You are more concerned with the content of your personality than your appearance, which causes you to be less conscious of the style of your clothes. You are more interested in comfort and the utility of clothing than the statement it makes. You are very vulnerable to praise and criticism. You tend to worry a lot, causing stomach problems."
]
      end
    end
end
