class SoulUrgeChallenge < ApplicationRecord
  has_many :charts
  has_many :users, through: :charts

  def short_description
    if self.number == 0
"Having a Zero Soul Urge Challenge does not mean that you will not encounter any challenges in your life. There may be times when you need to rely upon yourself to accomplish your goals, and there will be others when you'll need to ask for help. Sometimes you'll benefit from being social and other times you will need quiet and solitude to focus on what you're working to achieve. You should be responsible with your freedoms, and show others your compassionate side-just make sure that you don't let anyone take advantage of your caring nature. When it comes to business matters, make sure you allow yourself time for processing, and move forward on your decisions in an organized fashion."
  elsif self.number == 1
"The challenge of number one is to stand for yourself and to be independent person. People with this number challenge are prone to compare themselves with other people and to depend strongly on another opinion. The main challenge is to be true to yourself and value your individuality."
  elsif self.number == 2
"Number two challenge people are very easy to put out of balance as they are extremely touchy and sensitive. They think too much about the opinions of others. Their challenge includes coping with responsibilities, as they hate any sort of pressure and tend to hide or feel weak rather than to accept responsibility. If this number is manifested heavily, people are afraid of most of the serious decisions in life."
  elsif self.number == 3
"To overcome this challenge, one must become more social and not fear making mistakes around others. It can cause one to live totally #{“inside”} themselves."
  elsif self.number == 4
"Too much or too little attention is given to details; one must learn balance, dependability and how to focus on work or other matters at hand."
  elsif self.number == 5
"One must learn how to accept change and let go of the old to make room for the new. Another lesson is moderation; overindulgence in any pleasure can be dangerous."
  elsif self.number == 6
"Being a perfectionist and having unrealistic expectations of others can be difficult for one with this challenge. One must also find ways to be responsible to family and partners."
  elsif self.number == 7
"Developing patience and understanding by finding commonality rather than differences is at the root of this challenge. It’s important to develop faith in the self and others."
  elsif self.number == 8
"Number 8’s challenge is love to material things. They rely only on the material goods and status as the vector of their development. Money help them to add in self-sufficiency and self-appreciation. People like these can ruin their lives searching for illegal ways to multiply their finances. They need to find other sense of life and spiritual development."
  elsif self.number == 9
"One of the major challenges that people of soul urge number 9 faces is they allow people to walk all over them. While it can be great to see them look at the good side of others, they should also note all people are different individually, and thus, have their own paths to take."
  end
end

  def long_description
    if self.number == 0
[
"People who have life challenge number 0 are normally confronted with difficulties persistently. They also seem to get bombarded with difficulties from all directions. People with this number are normally mature, sorted and have their own preferences. They are also regarded to control and possess the good qualities of all the other numbers starting from 1 to 9 of numerology. Challenge number 0 is normally found in a person who is out of the ordinary. Their greatest challenge lies in sticking to a decision. They are able to compare and analyze different situations and come up with a solution but are not able to turn it into action. Thus they need to develop more faith in their ability of analyzing and should make a definitive decision and learn to stick to their choice. In early life this challenge number develops a person into an unmannerly child. In later life this person will be able to cross all obstacles and succeed.",
]
    elsif self.number == 1
[
"This challenge number makes one feel suppressed and dominated in the presence of others who are influential. Those people are normally parents or others with who this person competes and feels a threat of being overshadowed. The challenge number 1 imposes on others to be able to side-step when being dominated, but that without self- imposing or being very aggressive on others. Those with challenge number 1 should be able to control their destructive nature. Arrogance, pretentiousness, self-centeredness and vanity need to be shed by those who are under the influence of this number. Self-justifying, and resentment can be a problem with these people. They should be gentler in their behavior with others. Also follow a methodical and logical plan to achieve success. They should be able to keep their cool and rely on themselves to find solutions to their problems. They should bank on intelligence and own abilities and learn to be able to avoid being confrontational and quarrelsome.",

"Some of your internal struggles might include battles with low self-esteem or a lack of self-confidence. You may feel emotionally weak, at times, or as though you don’t have the strength or ability for authentic self-expression, yet moving through this block is a must if you are to achieve your potential. You need to actually demonstrate your originality and leadership. The 1 Soul Urge number demands that you evolve from feeling dependent to a place of independence. SO keep pushing your edges of what you think you’re capable of. Trust how intuitive you are and lead from the heart. This is your true compass. Beware of defaulting into defeat and staying there. That’s when you resort to self-absorption, cynicism, bullying, and battles with addiction. Your biggest lesson in life is around being knocked down, yet getting straight back up and carrying on. Deep down, you have the tenacious",

"You ARE meant to march to the beat of your own weird and innovative drum!"
]
    elsif self.number == 2
[
"People with their challenge number 2 are considered to be extremely emotional. They are not able to work with other people in a team because they fear being criticized, or maybe even worse, being disregarded or snubbed. They are also low on confidence and delve on self-doubt and uncertainty. They depend on the opinions that others hold for them and determine themselves according to that. They tend to turn sensitive and slide downhill. They need to be more positive in life and develop faith in themselves. They should also be able to turn their sensitive nature in their stride. Their keen sense of awareness of that which others are hardly able to perceive can be their strength. These people find it difficult to be assertive and make decisions on their own. Due to their being low on confidence, they are unable to accept positions of power and take charge. They should be able to take control of themselves and lead others. These people are wise as they pay attention to minute details and are observant. But they should also learn to let go and not take everything to heart. During these obstacles friendship will provide solace and comfort. These people are able to compromise and should plan for a gradual but steady growth in life rather than immediate success. Do not shy away from seeing the reality.",

"Some of your internal struggles might include an incessant need for acknowledgment from everyone around you. You yearn for external affirmation, yet one of your most important lessons is to develop a strong sense of self-trust. As an adaptable soul, you’re learning how to be in the middle of conflicting situations (something you actually despise) and find common ground and winning situations. It’s not easy. You’re also learning how to actually engage in groups and bring in your harmonizing presence without taking on everyone’s psychic garbage and emotional baggage. You must develop good boundaries, and adopting a good self-care practice (for instance taking weekly mini-retreats or a nightly energetic clearing routine) will really help you. You might walk a fine line with being passive or aggressive – indecisive or lacking focus – yet your calling is to become a peacemaker and harmonizing influence on whatever you touch. Understand that this Numerlolgy needs you to get out and socialize because when you isolate yourself, you suffer from pessimism, depression, and inaction. You’ll be tested with being overly sensitive and can be confrontational rather than a harmonizer. Basically, know that you’ll be challenged with the opposite of your calling – meaning, you can have trouble with relationships, be overly sensitive, and have trouble with compromise.",
]

elsif self.mnumber == 3
[
"People with challenge number 3 find it difficult to focus due to some psychological problem or simply sheer boredom. They are unable to excel at a specific talent and try their hands at various different abilities. These people are also shy and thus despite having the talent, creativity and gift of gab they are unable to express it. They are also unfriendly. They do realize their need to socialize in public but are unable to do so and thus tend to become very defensive about it. When this number is their first sub-challenge number, such people are introverts and loners in their childhood. With time they grow to be bizarre and thus are not taken into consideration by others.They also fear criticism. They could be good at acting or singing or at any other talent but will fear getting involved in any of these activities out of fear of being judged. Also these people express themselves negatively in front of others and shy away from letting the world know about their abilities. People with challenge number 3 should be able to be more social and should hone their creative side.",

"If you give up on your dreams and don’t use your talents creatively, it’s likely you’ll battle with depression. You may also find yourself traveling down some unsatisfying and potentially destructive or addictive pathways. You must pursue your true calling, so it’s imperative for you to make efforts to focus on your inner calling. Fuel yourself with training and just enough disciplined practice to gain the skills you need, without dampening your creative spirit. BELIEVE IN WHAT YOU MUST DO AND DON’T BE DETERRED FROM EMBRACING AND ACTING UPON IT."
]
elsif self.number == 4
[
"Some of your internal struggles might include rigidness, stubbornness, and a fear of taking risks. You must find ways to expand your focus and take some calculated risks or you’ll experience frustration because you haven’t achieved what you know you could achieve. The number 4 is all about coming to terms with limitations – working with them, understanding when you’ve created your own limitations, and working through and around whatever the perceived limitations might be, in order to meet your goals. You could avoid putting down roots, shy away from hard work, and avoid having a family of your own. Expressing emotion can be a struggle. Sometimes you can become so self-sacrificing that you become the martyr or tyrant (“My way or the highway!”). This stems from your need to control and also from your high level of expectation about your own performance—and the performance of others. Overcoming perfectionist tendencies could form a large part of your journey.",

"People with their challenge number 4 have work related problems. These people are unable to find the right work for themselves. They either do not find a job that is gratifying, or are inefficient at their work. These people are also irresponsible and careless. Their understanding of the world is far from actuality. Their competence and commitment towards their work needs to be improved in order to succeed in life. They should learn to be more patient and understanding. They should be more rational and develop a practical outlook towards life that is closer to reality. Learning to complete a task within a given time frame is also important. Those who have challenge number 4 as their first sub-challenge number will face obstacles in which their opportunities in their childhood will be thwarted due to financial constrictions. If this number is the middle sub-challenge number then such people are not easily trusted by others because of their irresponsible and impractical nature."
]
elsif self.number == 5
[
"This challenge number denotes indecisiveness and an ill-tempered nature. Such people are mostly unreasonable and temperamental. They are very impulsive by nature and thus get into trouble as they do not think about the repercussions before stating anything. They also need to control their irritable nature to be able to make strong bonds with others. In childhood this challenge number will pose problems in fulfilling education and will also thwart many career changes for the better. In the adulthood this challenge number establishes itself into an inability to make concrete decisions due to being very emotional. Such people also tend to be unstable due to their impulsive nature. Also these people are freedom lovers and cannot easily be bound. They need to learn to compromise with it. Change is pertinent for such people but they need to manage it in a controlled manner. However, they should also learn to thwart any feelings of irresponsibility. Their challenge is also to control their impulsive nature.",

"Some of your biggest internal struggles are likely to involve paralyzing fear. If you do find yourself struggling with the demands of the number 5, you’ll do battle with self-absorption, fearfulness, and emotional paralysis. Remember there’s truly nothing to fear but fear itself (as Franklin D. Roosevelt would say). The trick is to understand that because, for you, this lifetime is all about developing fearlessness, you’ll face heightened levels of fear throughout your life. Another challenge commonly facing the Soul Urge 5 is addiction. If you’re not able (or determined enough) to create a lifestyle that allows you a sufficient variety of experiences, you may try to seek them in other ways, like through drugs, drink, sex or shopping, for example. You must watch these tendencies in yourself, as they could really sabotage your potential. You may tend toward stirring up drama wherever you go, in order to feel something. Or on the other end of the spectrum, it’s not unusual for the person with a 5 Soul Urge to hunker down into their own little world, fearing even the most basic transitions or change. Some Number 5s have a tendency to discard relationships (or jobs or anything else) before they ever really get started. This fear of commitments can mean that you really miss out on the depth that is available when you stick at things. So it’s important that the art of discipline is learned at an early age, where possible, as this is a skill which will really serve you in later life."
]
elsif self.number == 6
[
"The challenge posed on people with this challenge number is to stop setting high standards for themselves and others. A person with challenge number 6 could be a perfectionist, but expecting the same from others may give rise to their problem. It is difficult for people around these them to match up to their expectations. Such individuals are therefore demanding, insistent, authoritative and inconsiderate towards others. These people also create friction in relationships and are not able to balance out situations. They should learn to live with love and peace. They should not try to control people as others will follow them only when they will feel that their opinions too have been considered and respected. Tolerance towards other individuals needs to be grown. Accept others the way they are and let them set their own standards and rules. Dominating others and trying to set them in their track is a common disposition of people with this challenge number. Their challenge is to be able to love others unconditionally and embrace them for their talents and lacks. Do not be rigid.",

"Some of your internal struggles might include self-righteousness, codependency, or meddling martyr (“Look at how much I do for everyone else and what do I get? Nothing!”). Your soul’s true calling is in healthy nurturing, compassionate detachment, acceptance of others (get past that perfectionism!), and adding beauty and your beautiful vision to the world. Living from the heart means putting yourself first – this is something you’d do well to remember! When you extract yourself from your self-imposed world of “shoulds,” you’re on the right track. You’ll have a tendency to lose yourself and your identity because you’re so busy taking care of others and taking over the responsibilities of others. Or alternately, you can default into the irresponsible side of the energy of the 6 and care only about yourself and what you want to do – and do it whenever you want to, despite the fact that you’re shirking your duties and responsibilities to those around you. The contradiction is that you need to feel indispensable to others and yet resent the fact that others rely on you too much. One of your specialties is damage control, so when things are moving along without trauma or drama, you have a tendency to either sweat it (while you wait for another fire to put out!) or you stir things up in order to have a problem on which to focus your energies."
]
elsif self.number == 7
[
"This challenge number poses a problem dealing with intense emotions. People having this challenge number feel the need of suppressing their emotions in the presence of others. If this number is the first sub-challenge number then it makes children to be introverts. They also tend to be obsessed and are completely detached from reality. When this number is the middle or the final challenge number, then such a person thrives on negative thoughts. They vent their feelings by continuously complaining and criticizing others. Many can suffer from some ailment due to their stifled grief. They are also unable to better their situation and thus keep complaining. They do not express their real feelings and hide it by a sense of false vanity. They thus are perceived in a negative way by others. They should have more faith on themselves and thus should try and build stronger relationships with others. Do not dwell on your limitations. Marriage thus should be delayed until this challenge is overcome otherwise it is bound to cause trouble in married life.",

"If you find yourself isolated to the point of withdrawing from the “outside world,” you’re straying too far from the constructive nature of your Number 7. The highest and best uses of your extraordinary mental talents are cultivating knowledge, processing it into new ideas, spiritual insight, or practical usage – and then adding your advanced intuitive wisdom to the mix. But this is a tall order! So it’s not uncommon for feelings of self-doubt to plague number 7s, especially if you don’t understand how important this last piece of the puzzle is. On the other hand, obsessive and compulsive behavior, and perfectionism can become problematic tendencies for number 7s, due to their highly idealistic natures. Some of your internal struggles might include your propensity to live in your head and intellectualize everything. With a 7 Soul Urge, you’re on a path of learning how to connect with yourself and others on an emotional and physical level. Because your comfort zone exists much more distinctly in the heady, data-focused, ideas-based realms, it’s vital for you to come back down to earth and connect to people in the real world.",

"When you have a strong sense of spirituality (however that manifests for you), you’re at your best. But without this higher calling, Number 7s can quickly fall into superficiality, skepticism, cynicism or even depression. Be careful about using sharp words, as you can hurt people without realizing it. This Numerology means you can be highly misunderstood or misinterpreted by others. You can give off an aloof attitude that others mistake for “snootiness”, feelings of superiority or just aloofness. You’re an extremely private person but you must try not to shut others out. This personality trait can easily sabotage the potential for extremely beneficial relationships and partnerships, both personally and in work and business. At your core, you’re a gentle soul and your heart’s desire is to truly know yourself and the mysteries of the planet – and to share your hard-won wisdom with the world."
]
elsif self.number == 8
[
"People who have their challenge number as 8 assume that only material accumulation can provide them with satisfaction. They thus exert themselves to gain material wealth, power, authority over others and status. They turn a blind eye to everything else. Thus this number indicates greed and acquisitiveness. The number indicates that there is a negative connotation with such people’s concern with material wealth. They perceive others by their possessions and status. They should learn to use their ability to gain status, power and money but not at the cost of neglecting other important matters of life. If this number is the early challenge number then as a child such a person must have been shrewd, manipulative and selfish. When this number is the middle or main challenge number then such a person will value material pursuits more than relationships. They should deal with the material world comfortably and not be aggressive about it. Focus on the other aspects of life such as relationships with friends and family. Learn to relax and enjoy in life.",

"Some of your internal struggles are likely to include too much(or too little) focus on money. Because so many of your life lessons will involve this form of energetic currency, its hold over you, and the part it plays in your life will be huge and ongoing. And because the people around you observe this in you (money is an emotive subject for us all) it’s likely that many of these lessons will be played out in public. You cannot help but be observed in so much that you do, which means the trials you face will often be faced on behalf of the collective. If you struggle with money, start by healing and establishing your sense of self, by defining and acting on your personal boundaries. This will serve to bolster your sense of self-worth, which may appear from the outside to be blooming with fortitude, is not always as strong as others think. When you are thriving financially and giving generously from your heart, you’re doing what your soul was born to do. But here’s a word of caution: Don’t allow the pursuit of money to overshadow your ability to build healthy relationships. You can, at times, be easily misinterpreted by other people because of your direct, factual and often opinionated manner. You can also become obstinate and stubborn, believing that you are the only one with certain capabilities or strengths. But if you listen to other peoples’ advice once in a while, you’ll realize that they can help you build your empire. Or if you’re working with the destructive tendencies of the number 8, you can turn into the ultimate doormat: self-destructive, sulky and wallowing in hapless victimhood.",

"Either too much or too little concern with financial and material matters is the hallmark of this challenge. It’s important to focus on people, not profits."
]

elsif self.number == 9
[
"Some of your internal struggles might trip over into the arenas of resentment, intolerance, or gullibility. You can also struggle with an inflated sense of idealism and find it difficult to ask for help or support. Understand that others may perceive you as arrogant or unapproachable. This is because people will often think you have it all together and perceive you to be the one in charge of situations, even if you’re new to the game. YOU’RE THE POSTER CHILD FOR “FAKE IT ‘TIL YOU MAKE IT!” Since you’re learning integrity and cultivating inner wisdom, you’ll likely end up being frequently tested on many levels. Yet because you’re usually the one who gives, gives and gives some more, these lessons are likely to involve how to give and to receive. This means there will often be an imbalance one way or another, in your life. Either you’re too much of a giver or too much of a taker. You need to be aware that people respond much more favorably to you when you connect with them through being an active and compassionate listener rather than a preacher, lecturer, or proselytizer. You often have an intimidating or intense quality to you, despite your big heart.",

"Some people do appreciate the kindness, there are others who like to tread on such people, and they should be wary of them. Another major concern is their immense generosity. Many people with the soul urge number 9 are known to keep giving, even if all their resources are depleted. They should take keep an eye on this generosity of theirs as it can destroy them. So, by creating awareness among such people, they can maintain healthy relationships with others. People having the soul urge number 9 are always on a quest to make the world a better place. When doing that, they sometimes tend to preach things in ways, and many others start to see them as preachers or priests."
]

    end
  end
end
