class SoulUrge < ApplicationRecord
  has_many :charts
  has_many :users, through: :charts


  def short_description

     if self.number == 1
"You have an overriding need to become #1 at everything you do in your life. When you look deep into your core, you have an underlying and pressing need to be independent, exert your individuality, and take the lead in whatever you set your mind to. You yearn to be the best at everything you do. You are likely competitive and enjoy pitting yourself against others – what better way to test your limits than to test them against someone elses? You may have perfectionist tendencies, expecting very high standards of performance from yourself and, in turn, also from others."
    elsif self.number == 2
"You have a deep need to love, be loved, and bring harmony to discordant situations. When you look deep into your soul, you have an underlying and pressing need to create harmony, balance, and cooperation. Love is the cornerstone of your heart’s desire, emotions are your lifeblood, and connecting to other people emotionally is how you make sense of the world. It’ll probably not come as a surprise to you that finding your perfect mate is important to you. The 2 is the number of partnerships. Because you hold this vibration at your core, you seek successful and satisfying partnerships in life, whether it’s romantic, business, or friendship. You’re here to learn how to develop your sense of relationship. It’s all about how to successfully understand and relate to others and to yourself. Understand that – like all aspects of Numerology – harnessing this energy is a goal. Often, the Soul Urge can feel as though it’s an underlying drive that you can’t explain – even to yourself. Yet it’s important to realize that to find real fulfillment of this number, you’ll likely experience more focused and intense challenges on the path to mastering these particular aspects of your heart’s desire."
    elsif self.number == 3
"When you look deep into your soul, you have an underlying and pressing need to communicate through creative self-expression. You need to do this, in order to inspire, heal, uplift, and energize others. However it manifests through your life, your ultimate purpose comes through best when you’re sharing your sense of optimism, enthusiasm, compassion, and joy. Your innate good-humour and cheerful nature makes you enormous fun to be around so it’s likely that you are never too far from a willing audience. At your core, you’re here to express your unique perspective and insight. You have a driving need to use your creativity through self-expression and this requires you to dig deep and get to know your own emotional life so that you can express authentically. You may have a tendency to skim across the surface and fall into the archetype of the fool, prefering to entertain and make people laugh rather than risk revealing your true self. But it is through doing this, that you’ll ultimately heal yourself and others. If there's anyone who's here to learn how to speak their truth, it's you."
    elsif self.number == 4
"You have a deep need to create something of value that people can find beneficial in their day-to-day lives. When you look deep into your soul, you have an underlying and pressing need to build something of lasting value. Whether it’s a family of your own, a business, or another enterprise, you’re all about stability and security. You’re hardworking, are likely a pillar of your community, and are imminently trustworthy. In fact, honesty, loyalty, and a trusting outlook are some of your most wonderful attributes. Know that you have the potential to be a stellar marriage or business partner."
    elsif self.number == 5
"When you look into your soul, it’s clear you have an underlying and pressing need for freedom, fun, excitement, and adventure. Down deep, you’re learning all about adaptability, progressive thought and action, and the wildness that this adventure of life is all about! You thrive with hands-on experiences and your task (and your challenge) is to develop your need for freedom into a constructive method – or to find freedom through self-discipline. It’s easy to do whatever you what, however you want, whenever you want, yet that isn’t the most realistic or productive path to true freedom. Your soul is asking you to find freedom even in the most restrictive circumstances, which means that sometimes (and for some Number 5s that will mean more often than for other people) you’ll be facing heavy limitations."
    elsif self.number == 6
"You have a deep need to provide loving service and a nurturing environment for yourself and your loved ones. When you look deep into your soul, you have an underlying and pressing need to nurture and serve, plain and simple. Whether it’s your family and loved ones or your business or community, you’re a creator of beauty, harmony, and balance. Check out this related post: meaning, mystery, and magic of the number 6. You’re the one with a polished presentation about you and have a magnetic quality that’s undeniable. Down deep, you are a walking “satellite dish” of emotional receptivity and while that’s a blessing, it can also be a curse. This is because you’re a natural counselor who can see the “bigger picture” and often get miffed when others can’t."
    elsif self.number == 7
"If your soul urge numbers are 7, it means you’re a highly spiritual person, a seeker of truth who is driven by the quest to find the facts. You’re obsessed about discovering your true self. You want to completely understand your personality, your abilities and the forces that drive you. You believe there is more to you than people see and you are not going to stop you figure these things out. You’re also interested in discovering the world around you. There’s a whole lot to explore; people, beliefs, tradition, and nature itself. The world poses numerous questions and you’re not simply going to overlook."
    elsif self.number == 8
"You have a deep need to manifest the financial security that will allow you the freedom to make a difference in the world. When you look deep into your soul, you have an underlying and pressing need to cultivate self-mastery in a profound way. Your heart’s desire is to succeed within business and organization, as well as in the realms of personal power and financial abundance, and you have the determination to do it! The number 8 is a relentless taskmaster and demands that you understand and employ all your abilities to achieve financial abundance while also giving generously to others."
    elsif self.number == 9
"You have a deep need to achieve a higher state of consciousness (in whatever form that means for you) and to teach others how to achieve theirs through giving and receiving fairly. When you look deep into your soul, you have an underlying and pressing need to engage in humanitarian service – to be of use to the greater good. You are idealistic and philanthropic and care deeply for the wellbeing of others. Yours is a spiritual path and you’re here to love unconditionally and with the utmost compassion, however that may manifest in your life."
    elsif self.number == 11
"Master Number 11 is considered the most intuitive of all numbers, and those with the Life Path Number 11 tend to be very sensitive and intuitive, with a deeper understanding of others and a natural sense of what is going on behind the scenes. For example, they will pick up on people's relationships and health without being told anything, and so they often end up working in the fields where they can use their gifts of intuition, and sensitivity to help others."
    elsif self.number == 22
"22 is known in numerology as the Master Builder. This means they are the grand visionary, the great architect of putting it all together. 22’s are highly intelligent people, with a common sense approach to life’s problems. They want to have a lasting affect on the world by building something that will remain long after they are gone or leading people to a better future. Soul Urge Number 22’s possess leadership capabilities that inspire loyalty. Followers are willing to go to the front lines for 22’s cause. Soul Urge Number 22’s are also creative diplomats who are idealistic and see the wide view of things. They can also be a bit eccentric. One thing 22’s have to watch out for is keeping their ego in check. It’s hard to be humble when you are making such considerable contributions to the world. They need to be careful not to give in to their more grandiose tendencies."
    elsif self.number == 33
"Life Path Number 33 is referred to as a Master Number in Numerology, and is considered the number of a Master Teacher. This individual's focus is on reaching the world and uplifting the loving energy of mankind. They are not concerned with personal ambition, and have great devotion to their cause. A birth date that reduces down to 33 is very rare. When it does happen you may be looking at a great and significant spiritual leader along the lines of the Dalai Lama (Life Path 22) or Gandhi (Life Path 9). Remember that 33 is the higher, double digit vibration of Life Path Number 6, a very nurturing and responsible number."
    end

  end

  def long_description
    if self.number == 1
[
"Following is not in your nature. The need for independence informs every aspect of your life. Other people look to you for direction, confirming your belief that you are the only qualified leader. Often you are right. You are intelligent and insightful. Your perspective does not always align with conventional views, something that those looking up to you respect. Your enthusiasm and commitment are infectious. Those who follow you quickly share your beliefs. Your belief that you are at the center of everything drives you to succeed. This self-centered attitude empowers you to treat everything you do with the seriousness required of a born leader. It can also work against you. Emotions are not your strong suit. You see the big picture rather than the individuals. This does not mean you eschew relationships. You are a loyal friend and fair in all your dealings, whether business or personal. Take care that you do not overlook the feelings of others. Your dominant nature can easily overpower others, including your partner and family. If you have a soul urge number 1, then working on developing friendliness and sincerity in your relationships will save you a world of trouble.",

"Your strong convictions require an audience. You do well in positions of leadership and authority, regardless of the field. Work hard and rise to the top. You will never be satisfied working on the lower rungs of the business hierarchy. Your work ethic and ability to make the right decisions even under pressure aids you in your quest for purpose. Ones make good entrepreneurs. As a one, you have the drive and the motivation to make a plan and stick with it. Your business ventures tend to be successful and profitable. You do not shy from responsibility, you embrace it. Your tendency to criticize without taking kindly to criticism means that you chafe at the bit unless you are the boss.",

"You need a supportive partner as a one. Your belief that you know best will cause conflict in your relationships. Loving a leader is not easy. Be patient with your partner and be sure to remind him or her how much you care and appreciate how patient he or she is with you.",

"Remember that not everyone wants to be led. Your weaknesses lie in the very qualities that make you such a compelling individual. The number of people who look up to you furthers your perception that you are at the center of everything. Your need to be the center of attention is a double edged sword. It drives you to push your own limits of success. It also comes across as arrogance. Surround yourself with people who are willing to share your beliefs. Sharing the spotlight is not in your nature. Competition can reveal an unflattering side of you that is best left unseen. Be wary of the dark side of this soul urge. You must try to avoid it in order to become the leader and innovator you want to be.",

"At heart, you have courage and fight. You are willing to go places other people fear and because of this confidence, others trust you and look up to you as a leader. Coupled with a charismatic personality, you have the potential to really break new ground. Your task is to develop your true, authentic self, and lead from this place (rather than ruling with an iron fist!) You must learn to develop your courage and to act independently. You have amazing insights and are a highly creative and innovative person. Underneath it all, you want to be the trailblazer, the pioneer, the original thinker – the one who pushes the envelope. And you can be! A Soul Urge Number 1 sets you up for the development of your sense of self and your willpower. Your journey through life is all about working hard… and playing hard.",

"Your compatibility in relationships depends very much on how you are fulfilling the yearnings of your Soul Urge Number in other areas of your life. You like to take the lead in love, and feel like you are in control. Yet your independent streak means you also need enough freedom to go your own way when the need arises! We’re not talking open relationships, just a long enough leash so that you don’t feel trapped! Your innate yearning for growth and achievement means that you likely need a partner who is as willing as you are, to evolve (in life and in love). For you, relationships need to be exciting! You may find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher. The numbers you have the highest compatibility are the 4, 8 and the 9. The numbers you have least compatibility with (though the ones where you have most to learn) are the 6 and 7.",

"Because of the Soul Urge 1s innate confidence, any position where you have authority and hold a managerial position is likely to suit. Yet, even if you don’t then people will probably still look to you for guidance and support. This number tends to inspire confidence in others! You may struggle with routine and discipline, so working for yourself, and/or running your own company could be ideal ways to get ahead. Because this number can struggle with perseverance (preferring to initiate new things, than continue with what has already begun) having a team of people to delegate to is an ideal way to work. The 1 Soul Urge calls you to take charge. Yet you need to learn to do this from a place of self-trust and stability. It’s important to recognize that in your life, you’ll be challenged with the opposite of your calling – meaning, you may have trouble taking the lead, trusting your ideas and opinions, and sticking to decisions. You may also struggle to feel naturally confident and optimistic when you feel you ‘should’. But these are all valuable parts of your path and offer opportunities to grow into your true calling. SO regard them as learning opportunities."
]

    elsif self.number == 2

[
"People with soul urge 2 seek deep and meaningful friendships. You want nothing more than to connect with others and enjoy their company. Your caring nature draws people to you, and your tact and diplomacy keeps them close. No one has ever accused you of being insensitive. Far from it. The feelings of others are almost more important to you than your own. Luckily, your affectionate, loving nature attracts people to you who care about you. The soul urge 2 nature is sensitive and emotional. This does not mean it is weak. If you are a soul number 2, chances are you’re very persuasive in your own way. Your diplomacy and ability to understand and empathize with others gives you your own persuasive capabilities. There is no need to dominate when you can convince others through kindness, compassion and trust.
You do not respond well when others attempt to make plans for you. You resent the implication that you do not have things under control. Your laid back nature requires like minded individuals. Overly strong or dominating personalities offend you.",

"You are a peacekeeper. Careers that bring out this part of your nature both fulfill you and cause you stress. You are also creative. These qualities, combined with your love of teamwork, make you a very desirable employee. You work well with others and while you enjoy being alone, you have difficulty staying on task. A social work environment is important for your well being.",

"Your love for others extends to a desire to be loved. You secretly wish that everyone loved and admired you, especially that special someone. Finding your romantic partner and having your feelings returned is the culmination of your heart’s desire. You see the good in others. Your faith in other people is sometimes misplaced. Twos tend to take it personally when someone lets them down. This causes problems in romantic relationships. Be open with your partner and accept that everyone makes mistakes. Taking things too personally is damaging for a relationship.",

"Your sensitive nature can backfire. Some twos are too sensitive. Don’t allow your ego to get bruised over the little things. Remember that not everyone is as emotionally intuitive as you. Being too easy going is also dangerous. Don’t be afraid to tell someone if they cross a line. Are you timid? Fearful? So are many other twos. Work hard to overcome these qualities as they can limit the number of wonderful people in your life.",

"Yours is the Soul Urge that needs relationships more than any other number. You crave connection, and have a strong desire for emotional intimacy. You are loyal and committed, and will often put others’ needs above your own. This is another place where boundaries are important – your emotional availability means you can end up exhausted. Many Soul Urge Number 2s are highly empathic, meaning that they absorb the energy and feeings of others as if they were their own. Taking the role of the peacemaker may come naturally to you – as a way to avoid conflict. Yet at times, your dependency on a partnership may mean you can exhibit traits of possessiveness and jealousy which, for the wrong person, could push them further away.",

"Your 2 Soul Urge encourages you to be of service to the “larger cause” – whether that’s your family, your company, or any other cause or group you feel strongly about. Down deep, you have a strong impulse to develop adaptability, patience, and to focus on serving win/win scenarios within a group. Work and careers that involve taking on supporting roles are well suited to this Soul Urge. Many PAs, secretaries, and assistants have the Number 2 in their charts somewhere. You thrive when you’re involved with other people and contributing to the group dynamics, whether it’s friends, work, family, or a community group, so working in larger groups, such as healthcare teams, or teaching may also bring fulfillment. Also worth considering are fields such as marketing, as relating to other people, and being able to “think” like others do come easily to this highly intuitive number. With the 2 as your Soul Urge, this number’s energy might be something only you can see or feel. Or alternately, you may “wear your heart on your sleeve” and show this more tender side of yourself more often than not. It ultimately depends on the other numbers in your chart and how those energies mix and match with your harmonizing number 2."
]

    elsif self.number == 3

[
"Your good nature is infectious. You are at the center of every exciting conversation. Your friends refer to you as “the life of the party” even though you don’t always mean to draw attention to yourself. People tend to find you inspiring and entertaining. Your ability to express yourself and your candid humor draw people in. You have a way of describing people, ideas, and experiences that paints a vivid picture for your listeners. You are a performer at heart and extroverted in nature. You are not afraid to speak your mind. This can result in a fair number of opponents. Luckily your gregarious nature lets your detractors’ words slide right off you. Secretly you enjoy the drama of confrontation. Sometimes you have a tendency to over do it. You can’t always stop yourself when you are nervous or particularly proud of an accomplishment. Too many words will get you in trouble. Be wary of running at the mouth in these circumstances. It will not endear you to others.",

"Your ambition and creativity mean that you are not satisfied with staying on the lower rungs. Low skilled work and subordinate status leave a sour taste in your mouth. You feel you are destined for greater things, and you are right. Limiting yourself as a 3 is dangerous. You do best when involved in large projects, or better yet, work for yourself. What career paths are 3’s best suited for? Your good nature and communication skills make you an exceptional orator. Public speaking, acting, writing, and teaching are excellent outlets for your skills. Self employment is appealing to you as a 3. Be alert to the risks of letting your creativity get out of hand. Without a proper outlet you lose focus. Choose a career that channels your creativity productively. You become disorganized and overrun with ideas without a proper focus.",

"You can’t help attracting romantic attention. Other people just want to be near you, which can be hard for your partner to accept. Your partner does not need to worry. People with soul urge number 3 tend to be extremely loyal.",

"Your effusive enthusiasm and tendency to rattle on are cause for concern. Make an effort to limit your words in stressful situations. Embrace career paths that make use of your creativity. Failure to do so makes you disorganized and unfulfilled. Keep your ambition in check. Ambition is a powerful force but can also distract you from some of life’s more important qualities. Truth is important to you. Don’t fall prey to the belief that truth is all important. The truth is not always helpful, especially when dealing with the feelings of others. The same is true of pride. Take pride in your accomplishments. Avoid pride of character.",

"Understand that, like all aspects of Numerology, the pure vibration of the 3 is a goal and as the Soul Urge, this feels very much like an underlying drive that you can’t explain, even to yourself. But because of the way our Universe works, in order to reach this goal you’ll experience more focused and intense challenges, whilst on the path to mastering these particular aspects of your heart’s desire. You may face harsh critics or come up against crippling self-doubt. But it is by moving through these obstacles that you’ll reach mastery of this number. Some of the deep, emergent qualities you bring to the table are beauty, possible eccentricity, excitement, and even potential fame. Do not hide these parts of yourself. Your amazing sense of wit and humor, and your lighthearted communication style is likely to be one of your most effective tools in helping yourself help others. But only when you’ve tapped into your own authentic sense of self-expression, will you be a true inspiration for others to uncover and express theirs. When you reach this place, you will be well on the way to fulfilling your heart’s desire.",

"Your compatibility in relationships will depend very much upon whether your partner shares your creative vision and your deep-seated urge for spontaneity and fun! Your need your relationships be stimulating and ever-evolving, in order to keep you interested at all. Unfortunately, it’s likely that when you feel the itch (be it 7 years or 7 weeks in) you’ll be looking around for more excitement elsewhere if your current pairing isn’t wild and passionate enough to keep your inner fire burning. Because of this, you may find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher. The numbers you have the highest compatibility are the 7, 5, 6 and the 9. The numbers you have least compatibility with (though the ones where you have most to learn) are the 3 and 5.",

"Often those with a 3 Soul Urge find that being “onstage” or out there in front of people doesn’t always feel natural, yet you’ll constantly attract opportunities that push you into the spotlight. For this reason, careers involving public speaking and performance of any kind may be a good match. Or they may not – perhaps finding ways to express yourself in more personal, one-to-one settings, or through art or writing may better suit you. Either way, finding a career in which you can be creative is imperative.",

"The 3 Soul Urge calls you to express yourself and help others do the same in the most positive, funny, joyful way possible. It’s important to recognize that you’ll be challenged with the opposite of your calling – meaning, you may have trouble managing your emotions, resist the spotlight, and struggle to feel naturally joyful and optimistic when you feel you ‘should’. But these are all valuable parts of your path and offer opportunities to grow into your true calling."
]

    elsif self.number == 4

[
"Your friends know you are a loving and stable influence. You can also be blunt and rude. You never mean to hurt their feelings. Your practical nature and desire for order sometimes overrides your ability to intuit others’ emotional needs. Emotional intelligence is not your strong suit. You have trouble intuiting the needs of others, especially those more driven by emotion. It is important for fours to remind the ones they love that they love them. Don’t assume your loved ones know how you feel. Make an effort to tell them how important they are to you. Your loved ones do not always cooperate with the ordered world you build for yourself. Avoid trying to enforce order on others. The attempt will frustrate both of you and can damage the relationship.",

"You crave order and stability. You are also quick to violate the law if you believe the law is wrong. Your rebel nature may not make sense to others. You are balanced and practical. What they do not understand is that you have very firm ideas about right and wrong and feel it is your duty to implement them. Effecting necessary change is as important to you as is upholding order. You desire to improve the world. Politics or a spiritual calling suits your nature and fulfills you. Money is only important to you in that it allows you to be generous to others. Your generosity leads others to believe you have more material wealth than you actually possess",

"You have a hard time opening up to others. This conflicts directly with the deep feelings of love and affection you feel for your partner. It will always be difficult for you to share your deepest secrets and feelings. The effort is worth it however.",

"There are several qualities in your nature you need to be cautious of as a 4. Your inability to open up and to trust others is damaging to your interpersonal relations. Your tendency to criticize does not enrich your life. It only offends others, alienating potential friends, allies, and lovers. Make an effort to appreciate the good in others. You have a hard time expressing emotion and so you compensate with generosity. Be careful about spending beyond your means. Sometimes a kind word is more meaningful than an expensive gift. Coonnecting with others is difficult for you. Push through it. Solitude is not good for people with soul urge number 4. You need other people to balance you out, no matter how organized you believe your life to be. Remember that disruption builds character. Embrace the duality of order. Order comes from chaos, and one cannot exist without the other.",

"Your heart’s desire revolves around being practical and hardworking. You are the systems-builder extraordinaire! You strive to keep order, and thrive on stability and security. The number 4 also brings in certain family-related wounds that will be central to your decisions and actions in life. Of course, everyone has “family issues,” yet part of your particular soul’s calling is to come to terms with yours, and to work to heal them. Often, the method to do this will involve creating order from chaos. This will likely mean providing a solid family environment or a stable lifestyle that you didn’t feel you received during childhood. Understand that – like all aspects of Numerology – the highest manifestation of this number is a goal. The Soul Urge can feel like an underlying drive that you just can’t explain – even to yourself. Yet it’s part of you. Also, understand that to get to a place of fulfillment, you’ll experience more focused and intense challenges on this particular path, to mastering these aspects of your heart’s desire.",

"Relationships with you, number 4, will always be committed, loyal and true. Because you care so deeply for the wellbeing of your family and community, your own romantic relationships form a part of this too. For you, love is about strength and creating a safe place to grow from. As a typical provider, you will likely attract people who need to be supported – be especially careful that you aren’t being taken for a ride in relationships. Even though your natural state is to give generously, it’s important to keep a balance. The journey of the Soul Urge Number 4 is also connected to healing familial and ancestral wounds, so it’s likely that your closest relationships in life will involve some deep soul clearing. Once you look at them through this lens, your patterns may begin to make a little more sense. Overall, you need security (though at times, you may express feelings of quite the opposite!) You will likely struggle with a partner expressing very free-spirited traits. Be careful of expressing controlling tendencies. It’s likely that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher.
The numbers you have the highest compatibility are the 6, 1, 8 and the 11. The numbers you have least compatibility with (though the ones where you have most to learn) are the 3 and 5.",

"Down at your core, you desire outlets for managing, getting organized, and creating a foundation from which to build your life or enterprise. THINK A LITTLE BIGGER. Don’t succumb to seeing work as a necessary evil – since work is a huge part of the vibration of the 4 (it’s the number of hard work!) – you might find that it takes you a while to settle on a career that suits you. So don’t settle for less than you feel passionate about, and love to do. Folks who have a 4 in their chart either have the tendency to work really hard from early on in their lives or they are the proverbial “slackers” who take their sweet time before they realize that they feel much better when there’s a focused plan, committing to the work hard it takes to get the job done. Make a concerted decision. Put down roots.",

"Careers such as teaching, mentoring and training could be especially fulfilling. Or anything where you are required to create systems – such as working in computing or programming. Yet your grounded qualities could also be much better suited to working out of doors, in landscape gardening or horticulture, especially if you’re someone who yearns for the great outdoors. With the 4 as your Soul Urge, the frequency of this number might be something only you can see or feel. Or alternately, you may already, naturally work with great tenacity, bask in checking off the goals on your punch-list, and revel in sharing your vast knowledge with others with great consistency! It ultimately depends on the other numbers in your chart and how those energies mix and match with your steady and hard-working number 4."
]
  elsif self.number == 5

[
"As a 5 you make friends quickly and easily. Keeping friends is more difficult. New people excite you. The effort involved in maintaining friendships does not. Your lack of consistency frustrates your friends and leads to friendships that end badly. It is hard for you to realize that this is your fault. You feel deceived and let down. Those with soul urge number 5 abhor loneliness. Luckily for you, you make new friends almost immediately. Use each new friendship as a chance to work on your tendency to get distracted. One day you will be ready for the long lasting relationships you crave.",

"Your adaptability and intuition make you easy to approach and confide in. Your friends love talking with you and being around your energy. This is why they get hurt when your attention moves elsewhere. Change excites you everywhere except your home. Your ability to embrace change depends upon the stability of your private world. You become very upset with that is disrupted. You hate when other people touch your things or rearrange them.",

"Your love of change and new ideas makes you an excellent entrepreneur, provided you make an effort to follow through. You love thinking of new ways to make money and enjoy the risk of new enterprises. All types of people interest you. Choose a career that excites you. A career that does not interest you quickly begins to stifle your creativity. Freedom seeking fives rebel against this. You will not stay long in a career that makes you feel trapped. Consider a job that requires travel or exploration. Your people oriented personality does well in fields where you encounter new faces regularly. Your ability to connect with others is invaluable to employers. Networking comes easily to you, and those you meet do not forget your energetic persona.",

"Your passion for freedom and inconsistent nature conflicts with your boundless ability to love. Finding someone who you trust and who understands the real you is difficult. The ease with which you attract others sometimes works against you. It is tempting to move on the minute things become difficult, especially when you have so many options. It is hard for you to be patient.",

"Your tendency towards impetuous action gets you into trouble. Take the time to think about your decisions and words. Your quick wit leads to a sharp tongue when angered. Your intuitive nature gives you an unfortunate ability to hurt others with your words, as you know exactly what to say. Constant movement energizes you. You do not like taking the time to relax. Your soul yearns for freedom and adventure. This is not always healthy. As a 5 you must try hard to train yourself to relax and slow down. Your energy does have limits. So does the patience of your loved ones.",

"At heart, you are fearless and feel a deep-seated yearning to explore the world. This number is an expression of curiosity and wonder and this craving needs to be satisfied! Most often in numerology, the number 5 brings with it the characteristics of intelligence, resilience, and spirituality. You are resourceful and deeply, intuitively connected to nature and the physical world; and because of this, you need your 5 senses to be constantly enlivened! But in order to live so freely, you need to trust that the Universe has your back. And it does – you’re never left out in the cold! You’ll always be the one with travel plans drawn up on the calendar or if you don’t have them there, I’ll bet you have some pretty long “wish lists” and Pinterest boards to go with every single one! You have an underlying need to experience other people, other cultures, and other ways of living outside of the traditional “white picket fence” ideal. In fact, this Soul Urge number often leads you on a frenetic roller coaster where at times, life can feel as though it’s coming at you without a filter.",

"In Numerology, Soul Urge Number 5s are often described as life’s storytellers. The essential skill of relaying a great tale comes naturally to you (as does having a wild imagination and a mind full of great tales to tell!) You are outgoing and tactful in your communications and have many friends and admirers. And whilst some may not love your impulsive nature, it certainly keeps life interesting and stops you from falling victim to the hum-drum of routine! Understand that – like all aspects of Numerology – this is a goal and as the Soul Urge, this vibration can feel like an underlying drive that you just can’t explain, even to yourself. It’s also vital to understand that you’ll experience more focused and more intense challenges on the path to mastering these particular aspects of your heart’s desire.",

"In the early stages, it’s likely that you find being in a new relationship exhilarating! But due to your fast-moving nature and constant desire for unique experiences, you may quickly lose interest and desire to move onto the next new thing. Your longer-term compatibility in relationships will depend very much upon whether your partner can afford you the freedom that you really need. Even finding a partner who shares your wanderlust could be challenging, as, at times, the confines of a relationship could even prove too much. But, if you can be open and honest about your needs, and remain faithful, there is no reason you cannot be in a strong, long-term relationship. As with most Soul Urge Numbers, you will probably find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher.Your most compatible numbers are the 3, 5, 7 and the 9. Your least compatible numbers (though the ones where you have most to learn) are the 2 and 4.",

"Ultimately, your soul’s gift is showing others how to live fearlessly through your example. The key to this, is to work with boundaries and certain parameters, or life could very quickly become chaotic and out of control – or reclusive and needlessly restrictive. So although this may seem counterintuitive to your adventurous spirit, boundaries will set you free! Careers in travel (of course), journalism, hospitality or positions in business which allow you to travel and be the master of your own timetable are likely to suit you. Anything that comes close to a 9 to 5 is going to feel suffocating to you, so you’ll be looking for a way out pretty quickly. For this reason, self-employment or entrepreneurship could suit you, but you must ensure you have a strategy and a red-hot work ethic before you begin, lest you give up when the going gets tough, in search of more exciting opportunities…"
]

  elsif self.number == 6

[
"Your caring, sensitive nature makes you an excellent friend. People come to you often for comfort and advice. You do your best to help your friends and family. Don’t worry about whether your advice is sound. You tend to dwell too much on the quality of your counsel when what really matters to your loved ones is your ability to listen and empathize.",

"Your love of caring for others makes you an excellent caregiver. Sixes are also creative and empathetic. Consider a career in health care if you have soul urge number 6. Counseling is intuitive for you and you can make a real difference in the lives of others. Care giving is not your only strong suit. You value beauty and peace in your home and work environment. Your nature is creative and artistic. Consider a career that embraces these qualities and stay away from jobs that require conflict and debate.",

"It is a mistake to view your faithful, caring nature as boring. Sixes make excellent romantic partners, especially in their youth. People are drawn to your aura. Your friendly nature is very attractive to others and they tend to respect you. You are satisfied with simplicity and your ability to intuit the needs of others makes you a talented partner. Those lucky enough to have a six in their life can attest to the pleasures of the relationship. You value fidelity and longevity in your relationships. Unlike other numbers, chances are you will find what you seek. Sixes tend to form healthy, long lasting relationships and marriages that continually fulfill them throughout their lives.",

"Too much of a good thing can be problematic. Don’t let your caring nature get the better of you. Take the time to take care of yourself. Expressing your own needs and desires is difficult for you. You find it much easier to listen to the needs of others. Remember that relationships work both ways. You appreciate when someone tells you what they need. Give your loved ones more credit and open up to them about your needs as well as theirs.",

"You spend most of your time reading your partner; every word, every action, and every reaction. When they do succeed in breaking through that wall, you want full honesty. You need to know that they’re telling you the truth. Trusting doesn’t come easily, so when you lose it, it may never come back. Asides your trust issues, you’re a lover. It may even surprise you to find out that you’re a hopeless romantic, but this uniqueness in character is the reason you’re such a complicated person and why you find the journey to self-discovery a truly interesting quest.",

"You’re in your element when you’re expressing gratitude, generosity, acceptance of others, and giving comfort to others in times of need. You express your soul’s urge through love and service. As such, work in the caring professions such as nursing, childcare, healthcare or alternative healing therapies will likely appeal to you. Yet it’s vital that you work to hold firm boundaries so that your own energy doesn’t get depleted. As one of the most creative numbers, any work where you are using your artistic flair will also bring fulfillment. In fact, as Soul Urge 6 people can tend to be people-pleasers, they often place their own creativity on the back burner whilst ensuring everyone else gets the opportunities. Being able to satisfy your creative side through work means less chance of frustration and martyrdom when family and other responsibilities take over in your spare time.",

"You’re in your element when you’re expressing gratitude, generosity, acceptance of others, and giving comfort to others in times of need. You express your soul’s urge through love and service. As such, work in the caring professions such as nursing, childcare, healthcare or alternative healing therapies will likely appeal to you. Yet it’s vital that you work to hold firm boundaries so that your own energy doesn’t get depleted. As one of the most creative numbers, any work where you are using your artistic flair will also bring fulfillment. In fact, as Soul Urge 6 people can tend to be people-pleasers, they often place their own creativity on the back burner whilst ensuring everyone else gets the opportunities. Being able to satisfy your creative side through work means less chance of frustration and martyrdom when family and other responsibilities take over in your spare time.",

"As a caring and generous partner, you have a lot of love to give. This core number is romantic and loving, with an innate understanding of what other people (aka your partner) need to feel not only cherished but to simply get to work on time! You desire nothing more than a happy family life! The other important people in life are this numbers priority, so you’re committed and prepared to work hard in a relationship. It’s likely you really need a partner who’s as invested as you are in the long term, but you’re also more than able to hold the domestic fort, if your partner needs more freedom. Just beware of slipping into pre-defined roles too early on – it’s vital you get space for self-care too.",

"Beware of partnering with someone who is more of a “patient” than a true partner because you’ll find yourself becoming an enabler rather than a nurturer. Remember that your soul’s mission is to balance and modulate your sense of responsibility – not overly responsible (meddling, self-righteous, perfectionist) and not overly irresponsible (self-centered, judgmental, controlling). You may find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher. The numbers you have the most compatibility with are the 3, 4, and the 9. The numbers you have least compatibility (though the ones where you have most to learn) are the 1 and 8.",

"With the 6 as your Soul Urge, all of this might be something only you can see or feel. Or alternatively, maybe you easily act with innate loving compassion, using your creative visionary abilities to create business and beauty? Whether you realize it or not, your forte is likely offering yourself and those around you a nurturing home environment and being a supportive “go to” person for friends and family. It ultimately depends on the other numbers in your chart and how those energies mix and match with your nurturing number 6"
]

  elsif self.number == 7

[
"You have a deep and profound need to develop self-trust, and to find your own answers to the eternal questions surrounding the meaning of life. You’re a true seeker and thrive on gathering information and using your profoundly powerful mind to analyze it. You dig deep and contemplate heavily. You’re an incredible researcher – a perfectionist when it comes to data collection – but the truth is, everything always comes back to your own inner wisdom.",

"Underneath it all, you have a burning need to seek out a deeper, spiritual understanding. Your heart’s desire leads you on a very “internal” journey. You probably feel like you’re on a very different wavelength than most people – at your core, you frequently question why you’re even here on the planet (yet again!) and can feel somewhat detached from the world at large.The number 7 can be highly introspective, so with this as your soul urge, you need a good deal of private “alone” time. You’re a person many people will never really truly know because you’re still attempting to figure that out yourself! But one of the main reasons for the introverted and contemplative quality of this number is that you’re constantly processing information, received via your exquisite skills of perception. Your life is shaped by a powerful collision between practical, tangible information, and how you make sense of it; and your incredible intuition, which defies logic. Your task in this lifetime is to integrate the two – your intellect and your intuition – into a harmonious team. This is a strongly felt need, which likely rises even above your thoughts. And it will take a lifetime to integrate these core aspects of yourself, and use them to effectively navigate the world in real-time. It’s vital that – like all aspects of Numerology – you realize that authentically expressing the vibration of this Number is a goal and at times it will be hard. You’ll experience more focused and intense challenges surrounding these themes. This is because this is how you’ll ultimately master these particular aspects of your heart’s desire, and it’s what you came here, to walk this path to do.",

"You need to know, and this urge will place you on a journey. Your life is a journey full of discoveries. You’re not headed for a destination because let’s face it, you probably might not be able to figure it all out in one lifetime, but this doesn’t deter you. You’re focused and you’re determined. People will see you as reclusive and reserved and that’s probably true. You’re not easily trusting, because you know people lie. You know people that smile for the camera but are simply backstabbers and fakes. This drives you to find comfort in your own company.",

"You’re not necessarily a lone wolf, you don’t dumb having people around, but you’d rather not have anyone than move with fake people. When you do find people you like, you keep them at arms length. Your walls are so high and impregnable that people who try to force their way into your life grow frustrated with time. Yet, when you finally let someone in, you give your all to them. You lay bare or at least you try to, because let’s face, even you are not quite sure who you are. Let’s simply say you try your best, but if you’re ever betrayed by people you trust, it’s going to take an awful lot of time and effort to trust anyone again. Like friendship, love is not easy for you. You’re indeed an emotional being, but you simply can bring yourself to trust people who like you. Even when you do get along with a partner, you’re cool with keeping things casual without investing your emotions. This way, you’re safe from getting hurt.",

"YOU’RE AN IDEALIST AT HEART – AND A PERFECTIONIST IN MIND! Your biggest lesson in life is to cut yourself (and others) some slack and embrace the perfection of the imperfection of virtually everything: From politics and the environment to the way your spouse leaves their clothes in a mess, or your kids don’t make straight A’s in school. You may find yourself in positions of responsibility early on in your life and that sense of responsibility will continue as you mature. Fairness is an important theme in your life – you often feel an underlying need to seek fair and equitable solutions to the injustices of the world. Understand that – like all aspects of Numerology – the Soul Urge Number manifests as a goal, and its energy can feel as like an underlying drive that you can’t explain – even to yourself. Yet it’s important to also understand that you’ll experience more focused and intense challenges on the path to mastering these particular aspects of path.",

"Your career path needs to be in sync with your inner self to help you find fulfillment. With your need to always find the truth, you’ll fit in well with careers related to science, data analysis, and fact-finding. Normally, you prefer to work alone. This is not to say you can’t work with people, but you feel you’re at your best when working alone. This attitude may also have much to do with your inability to trust people easily. You, therefore, believe you’re more likely to be successful when you work completely alone and unsupervised. With this in mind, you may want to consider a career as a freelancer. Freelancing means you don’t need to come in contact with people and can work completely on your own and in your own space. Whatever career you decide to go for, be rest assured that your attitude to find facts and make discoveries will lead you to excellence and fulfillment.",

"Unfortunately, your soul urge number means you’ll have to navigate through certain life challenges. Your idealistic views may see the perfectionist in you emerge. You won’t settle for less or leave things just as they are. You’re so focused on getting to the root of things that people around you may begin to find your behavior obsessive-compulsive. This behavior could also mean you take more time than required to complete tasks. it can be rewarding, but it may also be quite annoying. You may also find yourself withdrawing from the people around you. You’re so concerned with protecting yourself and heralding the validity of your ideas that people may begin to find your nature self absorbed. It is, therefore, pertinent to come down to people’s level and try to find common ground. People can be fake, but most times, they are merely seeking for relevance and approval, this tells you that your acceptance, albeit with caution, can go a long way with helping others find their feet.",

"Your compatibility in relationships will depend very much upon whether your partner is able to truly understand you. Close relationships can be a struggle for Number 7s, because emotional intimacy doesn’t come naturally to you, and the need for solitude is great. You dislike people who are too needy, yet attract many who are intrigued by you, and want to be close to you! You need your closest relationships to offer enough mental stimulation to keep you interested. So whatever the Soul Urge, Life Path or Expression Number of potential partners, they need to be on your wavelength or you’ll quickly get bored. It’s likely that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher. The numbers you have the highest compatibility are the 4, 5, 7 and the 11. The numbers you have least compatibility with (though the ones where you have most to learn) are the 3, 6 and 8.",

"Because of their solitary spirits, Soul Urge 7s often enjoy working alone. Your over-riding desire to gather knowledge and learn as much as possible means that you probably prefer working things out on your own before collaborating with others. Careers in research, analysis or IT could be a good match for this Numerology. Other good options could include the fields of science, engineering, computer programming or web design. Regardless of profession, to be truly satisfied in life, you must engage in activities that will stimulate your intellect and allow you to really get at the details of a situation or problem that needs to be solved. You may be the one in the family who handles all the complex paperwork surrounding caring for older parents, or perhaps you use your analytical mind to be the chess champion in seven counties! Whatever you do, your strong Number 7 vibration will not only make sense of the complexities of any and every situation but ensure you’re the person who holds the knowledge for everyone else.",

"With the 7 as your Soul Urge, this might be something only you can see or feel. Or alternately, you may be a masterful specialist in some area of expertise, the wise sage who people consult for advice and instruction, and someone who trusts the nature of their own existence fully and completely. It ultimately depends on the other numbers in your chart and how those energies mix and match with your probing and contemplative number 7."
]

elsif self.number == 8

[
 "With a Soul Urge Number 8, you must empower yourself by acting within the highest ethical code, and by becoming “the authority” in whatever you do. When you pull yourself up and out of difficult circumstances (and yes, you’ll have more than your share of those!) and into success, that is when your heart’s desire will be fulfilled.",

 "It’s unlikely that you’ll find true satisfaction without achieving some sense of material success. And while money is an important aspect of everyone’s life, when 8 is your Soul Urge Number you’ll certainly experience some intense issues galvanized around money. Either you have it and must use it consciously and wisely, or you don’t have it and really struggle to rise above the feeling that the Universe is conspiring against you, believing that if you only had some money, you’d happy. Or what’s more likely is that you’ll experience both extremes of this spectrum during the course of your life and be required to learn lessons from being in each position. When the 8 shows up, often you can have a lot of money during certain portions of your life, lose it or give it away, then have money again (and so on).",

 "So remember at all times that the 8 offers the energy of resilience, even when it feels rather devastating. And whatever you place your focused energy and desire on, using good ethics, hard work, and a generous spirit will expand almost magically.",

 "Your compatibility in relationships will depend very much upon whether your partner shares your vision to succeed in life and is able to offer you the support, resources (and freedom) to accomplish that vision. Because you’re someone who tends to put your career first and romantic relationship second, you may struggle to maintain the sense of emotional closeness with partners who really need it. You need your relationships not to be too demanding – if they get in the way of your other plans then real problems could ensue. But without love, what are you doing it all for? What does money, fame, and power mean, if you have no one to share it all with? Your lessons in money could well spill over into the realms of love, so it’s important that you don’t neglect this part of your life.",

 "It’s likely that you experience many different relationship dynamics throughout your life. Particularly in your earlier life, you may find many people want to be with you – the power of the number 8 is intensely magnetic. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher.",

 "Right out of the gate, you have authority issues. It’s almost as though you’re a magnet for hostile teachers, crappy bosses, and even lousy or challenging parent(s) or life partners. But the truth is, these are all part of a testing ground for you to learn – often through negative example – how NOT to be a good authority figure so that you can gain insight into how to embody healthy and effective leadership. It is possible that you meet a wonderful mentor, although this does seem less likely for you intense Number 8s. In any event, the point is that you're being trained and coached to be an influential and above-board organizer, manager, or leader.",

 "Because of your highly influential nature (whether you like it or not!) you must be sure to always act with integrity. You have exceptionally high ambitions and are always striving for a little more. But, if there’s a chance you’ll get caught out – for cheating the system, short-changing a client or running a red light – then you will! So don’t put yourself through the heartache of taking undue risks. In business, however, calculated risks are what it’s all about for you, so carry on, and you’ll always do well.",

 "A large part of this vibration is learning to take the rough with the smooth. Just like the flowing, infinite line that makes up the timeless single digit as it’s written, you will always come back to top position. On the way around, though, you will need to roll with the punches. With the 8 as your Soul Urge, these qualities and characteristics may be something only you can see or feel. Or alternately, you may already be a masterful money manager, a giving philanthropist, a powerful and achievement-oriented organizer, or any other conduit for helping empower others. It ultimately depends on the other numbers in your chart and how those energies mix and match with your intense and power-focused number 8."
]

elsif self.number == 9

[
"The Soul Urge 9 is a wise, compassionate and globally-conscious number to have in your Core Numerology Chart. Sometimes referred to as the Heart’s Desire or Soul’s Desire, this core number contains powerful insight into your deepest and most eternal and spiritual, motivating forces. Whilst your Life Path Number describes the direction of your journey through life, and your Destiny, or Expression Number reveals your gifts, talents, personality and unique offerings to the world, the Soul Urge puts you back in touch with your essence. It’s a special part of Numerology that can bring real clarity around your mission in life, and help to uncover your purpose. So if you’re looking for answers, the Soul Urge is quite often the missing piece that provides them.",

"NUMEROLOGISTS UNDERSTAND THAT 9 IS THE NUMBER OF COMPLETION. It’s the number of self-sacrifice, of the old soul, of letting go, of releasing attachments, and of loss. It’s also the number of “limited rewards.” Meaning, you act and give without immediate thought of reward or gain. This isn’t to say that you aren’t lined up for a life filled with all the great things the material world has to offer. Yet it does indicate that luxury or money as the ultimate goal isn’t on the cards – money can be a byproduct of your humanitarian-inspired service yet is not the singular focus or goal.",

"As a Soul Urge Number 9, your life could be described as a life-long course in the “Art of Zen-Buddhist Living.” Meaning, you’re being asked to stay in the present, release the past without bitterness, and to move into the future with curiosity and an open heart. Sound easy? Hum . . . not so much. You’re at your optimum when you’re tapping into your creativity, sensitivity, and selflessness. This Soul Urge number is a powerful one, demanding that you learn to release attachment and move forward using your talents, creativity, and compassion to make the world a better place. Serving the greater good is your motivation.",

"Since one of the big reasons you’re here is to be the champion for the underdog, often you find that you yourself are the outcast or misfit. Or perhaps you simply relate strongly to those who are not in the mainstream, who are quirky, ostracised or underprivileged; or for any other reason find they are placed beyond the margins. Because of this, working for charities, environmental or social justice organizations or even volunteer groups would certainly suit you. Animal and children’s rights and political activism, as well as the more traditional change-making arenas of law, social services and the healing arts are all professions in which you could thrive. Arts and Crafts may also provide an outlet for your creative expression, and serve to spread your ideal, healing visions to more people.",

"'YOU’RE THE POSTER CHILD FOR “FAKE IT ‘TIL YOU MAKE IT!' Since you’re learning integrity and cultivating inner wisdom, you’ll likely end up being frequently tested on many levels. Yet because you’re usually the one who gives, gives and gives some more, these lessons are likely to involve how to give and to receive. This means there will often be an imbalance one way or another, in your life. Either you’re too much of a giver or too much of a taker. You need to be aware that people respond much more favorably to you when you connect with them through being an active and compassionate listener rather than a preacher, lecturer, or proselytizer. You often have an intimidating or intense quality to you, despite your big heart.",

"As a caring and compassionate partner, you have a lot of love to give whilst being flexible, interesting company and very open to whatever others need. However, you must try not to be too condescending, believing yourself to know better what your partner needs, than they themselves do. Working on genuine, open listening will certainly serve you in all relationships; as will learning the balance between giving an receiving. Otherwise, you may find you are taken for granted and your relationships become co-dependent. You may find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher. The numbers you have the most compatibility with are the 3, 6, 7 and the 9. The numbers you have least compatibility (though the ones where you have most to learn) are the 4 and 8.",

"Know that your 9 Soul Urge is a profound journey that offers you multifaceted opportunities to touch the lives of others and heal some of your own deepest wounds. At your core, you’re a gentle soul and your heart’s desire is to serve others and leave the world a better place while you’re here and when you’re gone. With the 9 as your Soul Urge, this might be something only you can see or feel. Or alternately, you may use your creativity freely and passionately, act with compassion, and serve the higher good in a substantial way. It ultimately depends on the other numbers in your chart and how those energies mix and match with your compassionate and humanitarian-focused number 9.",

"Soul Urge Number 9’s are charismatic and compassionate. They are those who strive to make the world a better place. Humanitarians and philanthropists, Soul Urge Number 9’s care deeply about the fate of mankind, and want to help so much that it often involves self sacrifice. You will see Number 9’s in the helping professions as psychologists and therapists.",

"Soul Urge Number 9 people are very sensitive, and can be overly emotional. They want to create harmony in the world and make it a more beautiful place, so they are upset by conflict. They are peacemakers, and enjoy traveling and learning about others viewpoints. They enjoy finding common ground with others and meeting in the middle. Soul Urge Number 9’s have high ideals and are intuitive people who give freely of themselves. One of their negative traits is self-righteousness, because they are truly baffled by those who don’t share their altruistic viewpoint. As they age they need to learn to have patience with people who don’t share the same community spirit."
]
  elsif self.number == 11
[
"You have a deep desire to reach for higher states of consciousness, and on your way there, you must learn to develop authentic and satisfying relationships. Look deep into your soul, you’ll see that you have an underlying need to evolve spiritually. But there’s a catch. With the number 11 as your Soul Urge, you’ve got your work cut out. It will be hugely beneficial for you to realize at the offset, that your soul’s mission will truly take a lifetime of development, so pace yourself. Your heart’s desire requires deeply felt experiences and through the course of your life, you will be tested over and over again. The ultimate lesson of the Soul Urge Number is that life is a marathon, not a sprint. There is an ongoing irony attached to Master Numbers, because on discovering numerology, many people want to see Master Number drawn up in their chart, thinking that a Master Number is somehow superior to a “regular” number. Untrue. A Master Number indicates that before incarnating, you opted into this lifetime on Earth with higher potential, yet with more intense challenges. These challenges will often manifest as life-long feelings of internal (and sometimes external) nervous tension, feelings that you’re never doing enough, being enough, doing it right, or living up to your potential. Yet those with Master Numbers are the ones being called upon to step up and take the lead in some fashion, to think bigger, and to make a mark, so it’s not an easy road. So if you’re working through life with a Master Number, don’t expect it to be easy … And if you’ve yet to decode your personal numerology chart, be careful what you wish for! There’s an undeniable intensity related to carrying the Master vibration, so it’s extremely important to know how to optimize and manage it, so you don’t crash-and-burn. Attempting to shine too brightly too rapidly, or suppressing, sublimating or ignoring your mission can both be painful routes to self-sabotage, and need to be avoided…",

"For you with an 11/2 Soul Urge, it means that the foundational energy of your deep desire resides with the number 2. You’re a mediator, a diplomat, and a curator of love and relationships. You express incredible emotional sensitivity and are the master or mistress of patience. But in addition to this, you contain the master number powers of the 1, in double intensity! The 1 is concerned with YOU, and making a mark in the world, coming first and championing above all else. The 1 contains the driving energy of initiation, leadership, innovation, independence, and is often the quirky individualist. The 1 seeks to take the lead while the 2 seeks to be the supportive power behind the throne. It’s as though you’re a Siamese twin, yet your twin is the Yang to your Yin.",

"You bring a heightened and refined energy to whatever you do and yet here is the inherent frustration: What you bring to the mix is somewhat intangible. And therefore it’s difficult to trust that you’re on task or having any significant impact because what you do best is primarily etheric and energetic. You’re a messenger, but one of the spiritual kind. As an example or a metaphor, let’s say you’re an artist – a dancer. You perform for an audience and many people come to watch you. As they experience the way you move, there is something that is affected inside of the person watching – something changes, something that even they don’t understand, let alone are able to enunciate. Yet your work has shifted them in an unspeakable way that will be a part of their lives forever.",

"Underneath it all, you are the “wounded healer” and your gift is to serve as an inspiration to evolve, in whatever form you choose. This may be through parenting, your career, your devotion to pets or causes, or any other aspect of life where you feel a deep connection. Know that you have gifts in the realm of artistic creativity. You’re at your optimal when acting upon healthy emotional and energetic boundaries, serving the needs of a group dynamic, and developing your relationship with yourself, with others, and with the spiritual realm. The Soul Urge 11 is a powerful number, demanding that you learn how to level your ego, trust your intuition, and serve as a conduit for spiritual energy to move and speak through you.",

"Your compatibility in relationships will depend very much upon your partner’s patience and understanding of your spiritual quest. But this isn’t to say relationships should be neglected – one of the missions of this master number is to understand the intricacies of creating and maintaining a healthy and successful relationship. Because of this, you may find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher. Your most compatible numbers are the 1, 2, and the 22. Your least compatible numbers (though the ones where you have most to learn) are the 3 and 5.",

"Know that your 11/2 Soul Urge is a profound journey that offers you multifaceted opportunities to create loving environments, dig deep into relationships, and bring an evolved and spiritually heightened energy to all of your interactions. At your core, you’re a spiritual messenger who is highly intuitive, probably psychic and certinly and creative. But with the number 11/2 as your Soul Urge, this may be something only you can see or feel. Or alternately, you may tap into your loving diplomacy, heightened creativity, and super-charged spirituality in a hugely substantial way. As with all of numerology, it ultimately depends on the other numbers in your chart and how those energies mix and match with your inspired and spiritually focused number 11/2."
]

  elsif self.number == 22

[
"When you look deep into your soul, you have an underlying and pressing need to evolve spiritually. But there’s a catch. With the Master Number 22/4 as your Soul Urge, you’ve got your work cut out. It will be hugely beneficial for you to at the offset, that your soul’s mission will truly take a lifetime of development, so pace yourself. Your heart’s desire requires deeply felt experiences and through the course of your life, you will be tested over and over again. The ultimate lesson of the Soul Urge is that life is a marathon, not a sprint. It’s funny because most people want to have Master Numbers in their chart, thinking the Master Number is superior to a “regular” number. But this is just not so…. A Master Number indicates that before incarnating, you opted into this lifetime on Earth with higher potential, yet with more intense challenges. These challenges will often manifest as life-long feelings of internal (and sometimes external) nervous tension, feelings that you’re never doing enough, being enough, doing it right, or living up to your potential.",

"Yet those with Master Numbers are the ones being called upon to step up and take the lead in some fashion, to think bigger, and to make a mark, so it’s not an easy road. So if you’re working through life with a Master Number, don’t expect it to be easy … And if you’ve yet to decode your personal numerology chart, be careful what you wish for! There’s an undeniable intensity related to carrying the Master vibration, so it’s extremely important to know how to optimize and manage it, so you don’t crash-and-burn. Attempting to shine too brightly too rapidly, or suppressing, sublimating or ignoring your mission can both be painful routes to self-sabotage, and need to be avoided. There’s an undeniable intensity related to carrying the Master vibration with you and therefore extremely important to know how to optimize and manage it so you don’t succumb to the “crash-and-burn” that can result when you attempt to shine too brightly, too rapidly – or the self-destruction that can result when you’re avoiding or sublimating your mission.",

"For you with a 22/4 Soul Urge, it means that the foundational energy of your soul’s desires aligns with the archetypes of the number 4. You are the ultimate teacher, a developer of strong systems, and a purveyor of hard work, while always managing to meet clearly defined goals. But in addition to this, you contain the master number powers of the 2, in double intensity! It’s as though you’re a Siamese twin and your twin is the Yang to your Yin. The 2 is all about diplomacy, patience and love, and is highly emotionally sensitive; while the 4 is all about gathering knowledge, and building and maintaining the systems and foundations which keep life contained.",

"As Numerologist Glynis McCant’s observes, the 2 and the 4 are “business” numbers: The 2 is in the business of love and relationship and the 4 is in the business of security and stability. Whilst the energy of the 4 is most related to limitation and feels safe and comfortable with rules, often seeing things as “black or white”; while the energy of the 2 is most directly related to the emotions and focuses first and foremost on the needs of others. So can you see how there might be a few issues along the way!?",

"Many numerologists will say that the Master Number 22 is the most powerful force in Numerology. Its energy carries with it a potent ability to manifest great things, yet the requirements for success are focused goals, organization, and doggedly following step-by-step processes. It’s vital to understand that this isn’t “slapdash” sort of energy. The Soul Urge brings the frequency of the slow and steady progress needed to build something solid, tangible, and useful.The Soul Urge 22 comes to work early and goes to bed late (metaphorically speaking). If you expect this to be a light frolic and an easy time, you’ll be in for a shock! Yet this is the energy that your soul chose for you to work with, in this lifetime. If you can nurture the expectation of core feelings of satisfaction and purpose, whilst taking the time, energy and planning to get from point A to point Z, then you’ll be using this powerful energy optimally.",

"You’re at your optimum when recognizing and blazing through limitations – both external limitations and limitations that are self-imposed. This Soul Urge number is a powerful one, demanding that you learn how to focus and manifest in the practical world. This is important: Without bringing your grand ideas to actuality, and expressing your personal breakthroughs by actually building something real in the world, you are not truly fulfilling your potential. Almost, but not quite.
Your real gift comes in being an example to others and teaching through what you do. The very best way you can teach and uplift others is by example.",

"Your compatibility in relationships will depend very much upon your partner’s patience, care and ability to understand your need for a secure, committed foundation as well as your need to be out there doing good in the world. As a highly loyal and exceptionally trustworthy partner, you expect the same in return. But your potentially turbulant path through life means that you may not be always able to give as much time and energy into personal relationships as you would like.
Hence needing an understanding partner. Because of this, you may find that you experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a teacher.The numbers you have most compatibility with are the 2, 4, 6 and the 22.
The numbers you have least compatibility with (though the ones where you have most to learn) are the 3 and 5.",

"Know that your 22/4 Soul Urge is a profound journey that offers you multifaceted opportunities to create a solid, steady, and stable home environment while also creating things of lasting value in the world. Whether that’s by using your teaching and knowledge skills or creating actual products, what you do with your life will go on to benefit people’s everyday lives. At your core, you’re a spiritual guide who is highly intuitive and also imminently practical. With the 22/4 as your Soul Urge, this might be something only you can see or feel. Or alternately, you may tap into your masterful teaching, embrace your heightened ability to work hard to achieve goals; and make positive use of your super-charged spirituality in a substantial way. It ultimately depends on the other numbers in your chart and how those energies mix and match with your inspired and spiritually focused number 22/4."
]
  elsif self.number == 33
[
"You have a deep need to bring an elevated form of loving service to the world. When you look deep into your soul, you have an underlying and pressing need to evolve spiritually – no matter how you define it. Yet here’s the catch. With the Master Number 33, you’ve got your work cut out for you. It’s beneficial to understand that this will truly take a lifetime of development, so pace yourself. Your heart’s desire requires deeply felt experience and tests you over and over again. This Soul Urge is a marathon, not a sprint. It’s funny, because most people want to have Master Numbers in their chart, thinking the Master Number is superior to a “regular” number. This is just not so. Yet let me explain: The Master Numbers indicate that you opted into this lifetime with higher potential, yet also with more intense challenges. So honestly, when you’re working with a Master Number, it ain’t easy. So be careful what you wish for! This translates into life-long feelings of internal (and sometimes external) nervous tension, feelings that you’re never doing enough, being enough, doing it right, or living up to your potential.",

"And those with Master Numbers are always being called upon to step up and take the lead in some fashion, to think bigger, and to make a mark. There’s an undeniable intensity related to carrying the Master vibration with you and therefore extremely important to know how to optimize and manage it so you don’t succumb to the “crash-and-burn” that can result when you attempt to shine too brightly, too rapidly – or the self-destruction that can result when you’re avoiding or sublimating your mission.",

"Yet the basic foundation it needs can take literally years of trial-and-error to form the basis from which to build, and then act. It is your deepest and fondest desire with a 33/6 Soul Urge to act upon a deep sense of joyful loving service – and to use your heightened creativity and love of beauty to the fullest. And you wrap it all up with a super-responsible bow!",

"The Master Numbers are innately in conflict with themselves. What does this mean? For you with a 33/6 Soul Urge, it means that the foundation of your deep desire resides with the energy of the number 6. You’re the nurturer – the magnetic visionary, justice seeker, and master or mistress of the domestic realm. Yet then you must add on the double 3. It’s as though you’re a Siamese twin and your twin is the Yang to your Yin. The 3 is all about creative self-expression, communication, optimism, and emotional sensitivity. You crave creativity and connection. The 33/6 is a rather enigmatic calling. It’s as though your soul is asking you to elevate your thoughts and actions into the “Mother Teresa” realm while also being dynamic, creative, and joyful in the process. So try that on for size!",

"Can you see how there might be a few issues along the way? It’s a constant push/pull between wanting to be of service and help and heal others – and yet you might also find that your perfectionism and judgment of others get in the way. The Master number is asking you to commit – to step into the spotlight, into leadership positions, and trust in your ability to provide joyful and helpful service to a larger audience in whatever form you choose. It’s a constant wrestle with letting go of self-righteousness and control while infusing love and service into all you do. You’re perpetually riding the teeter-totter of “I want to heal the world” and “The world doesn’t deserve what I have to give.” Master Number 33 is the conduit of joyful, loving, and nurturing service. Yet you can easily tip into the martyr role. Rather than being helpful you can opt for meddling. Rather than loving you can judge harshly and critically. Understand that “Master” actually means “Teacher,” not someone who’s superior, the boss, or a slave driver! As a 33, your basic “Master Number 33 Soul Urge 101” Class is to master self-care. You must learn to know and love yourself first before you can extend your gift of love and service to others.",

"In relationships, you can likely swing from being highly attentive and affectionate with your partner, to needing your own space. You are naturally empathetic, so good boundaries are key (as is a partner who respects them). The underlying frequency of the 6 means that family is hugely important to you, in fact you are devoted to the! Yet you must also take enough time to nurture your own creativity. So it’s vital that you have a partner who understands this, lest your energy levels become depleted. It’s likely that you will experience many different relationship dynamics throughout your life. The Soul Urge Number of each partner you meet will teach you a lot about yourself, so ensure that you regard each relationship as a master teacher. The numbers you have the most compatibility with are the 3, 4, and the 9. The numbers you have least compatibility with (though the ones where you have most to learn) are the 1 and 8.",

"Know that your 33/6 Soul Urge is a profound journey that offers multifaceted opportunities to inspire people with your joyful service and creativity – whether that’s by acting, music, medicine, counseling, being a homemaker or any other creative endeavors. At your core, you’re a selfless spiritual guide who is highly intuitive and infinitely loving. With the 33/6 as your Soul Urge, this might be something only you can see or feel. Or perhaps you easily tap into your nurturing disposition, emotional self-expression, and service? Making positive use of your super-charged spirituality could already make up a substantial part of your life. It ultimately depends on the other numbers in your chart and how those energies mix and match with your responsible and nurturing number 33/6. Understand that – like all aspects of Numerology – the higher aspects of this number are a goal. It can often feel like an underlying drive that you can’t explain – even to yourself. Yet it’s good to be aware that you’ll likely experience more focused and intense challenges on the path to mastery."
]
    end
  end
end
